bridges = []
persistence_dir = '/tmp/tmp.BM8H3lE45C/tryorama/Y5iZxU'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = '6261170b-2064-4920-be43-98cc7ca1d68b'
keystore_file = '[UNUSED]'
name = 'phil::6261170b-2064-4920-be43-98cc7ca1d68b::39c7522a-0cf4-4eae-abe9-49ba89a8b4ed'
public_address = 'HcSCj6nE6yznrxgn9xjsVDO5M9Ycb6c8dhYjcFYcTuvjadyjE47mKk36PpPsjwi'
test_agent = true

[[agents]]
id = '41553681-4c82-4c8c-87bb-ae2a3d2ba4cc'
keystore_file = '[UNUSED]'
name = 'phil::41553681-4c82-4c8c-87bb-ae2a3d2ba4cc::39c7522a-0cf4-4eae-abe9-49ba89a8b4ed'
public_address = 'HcScjePOpujax894rmsMhPUkOvsmh5actfC3TS4G55sXe7prrByyGTCQzog4nez'
test_agent = true

[[agents]]
id = '4b7641fe-145d-4217-9768-1e0bff70fdf5'
keystore_file = '[UNUSED]'
name = 'phil::4b7641fe-145d-4217-9768-1e0bff70fdf5::39c7522a-0cf4-4eae-abe9-49ba89a8b4ed'
public_address = 'HcSCIjjNK4GgjthdykagF6NuMUC3aakag9RF4HNpoZob6ekiiKm35o8uHbbjgur'
test_agent = true

[[agents]]
id = 'ef5ba968-0048-4135-b831-a86b615a89b2'
keystore_file = '[UNUSED]'
name = 'phil::ef5ba968-0048-4135-b831-a86b615a89b2::39c7522a-0cf4-4eae-abe9-49ba89a8b4ed'
public_address = 'HcScjt6zBKB3RyqnwcHjmNZOw5jpmv4eeyksAnJMktsrx4hex7bVCA8fRdb4gwr'
test_agent = true

[[agents]]
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'
keystore_file = '[UNUSED]'
name = 'phil::57c01ed8-30ae-4fca-b6f9-40192821fed2::39c7522a-0cf4-4eae-abe9-49ba89a8b4ed'
public_address = 'HcSCIN3659OsG36FZp7GsK6859sMRq4n69THE4eisorzwcxuoceRtYTptyw6c4r'
test_agent = true

[[agents]]
id = '164449a2-e7d4-47dc-acc8-2fe317b8d9fe'
keystore_file = '[UNUSED]'
name = 'phil::164449a2-e7d4-47dc-acc8-2fe317b8d9fe::39c7522a-0cf4-4eae-abe9-49ba89a8b4ed'
public_address = 'HcSCJ7SRnOAEo8zfngnfOpcGo4No8upwivYh77QMTJB9x4u49AuQ368g4t5S3uA'
test_agent = true

[[agents]]
id = '95569e2e-0de2-4073-8a7d-579f87534c04'
keystore_file = '[UNUSED]'
name = 'phil::95569e2e-0de2-4073-8a7d-579f87534c04::39c7522a-0cf4-4eae-abe9-49ba89a8b4ed'
public_address = 'HcScIfKnthw5a6k3gm7QHYrgqXKgnm7zdgStGGx5Tvn9nqobf9k7Vn5xja5V8zz'
test_agent = true

[[agents]]
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'
keystore_file = '[UNUSED]'
name = 'phil::a23de7fe-bff7-4e6e-87f0-f4c44d038888::39c7522a-0cf4-4eae-abe9-49ba89a8b4ed'
public_address = 'HcSCiBfi7Vfqk33diyhEhw3yhuciep5buO3xtAQVhfq8m3ncMjQP6xhBOgdsxdz'
test_agent = true

[[agents]]
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
keystore_file = '[UNUSED]'
name = 'phil::e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a::39c7522a-0cf4-4eae-abe9-49ba89a8b4ed'
public_address = 'HcSCjtWmdebw3am7nopO75aiR3JS5cmn7dI8iQJ5QBYyrapkmOrZ6a6kR4Dz35r'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'phil::fields::39c7522a-0cf4-4eae-abe9-49ba89a8b4ed'
public_address = 'HcScIaVupB75oebcpfCz8kqsC4Baco8dk9HHQxDO39f6Wx8aczfjgYJHis6thsz'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'phil::personalinformation::39c7522a-0cf4-4eae-abe9-49ba89a8b4ed'
public_address = 'HcScj9K9ZtqfgqemdyiyqECH73mSnrw4whvyK6Y7SMbq94nyB5xaPA55cKuiiva'
test_agent = true

[[agents]]
id = '0d765fcf-118f-4122-8f03-f5f9ba74e7fa'
keystore_file = '[UNUSED]'
name = 'phil::0d765fcf-118f-4122-8f03-f5f9ba74e7fa::39c7522a-0cf4-4eae-abe9-49ba89a8b4ed'
public_address = 'HcSCjPnQPCgpd9747k6CmNoPIpZdmnifrktoqpRamfnkorv4zzuSdOX6oijwx4i'
test_agent = true

[[agents]]
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
keystore_file = '[UNUSED]'
name = 'phil::0098d2a1-5668-4a5a-8ef8-503d58dd38ce::39c7522a-0cf4-4eae-abe9-49ba89a8b4ed'
public_address = 'HcScJHt3z8CJ48ktgsv79xgKXBxZtsgn5tkzRODtiz6yxuasW65Kg9VDuTzeona'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmQ4ZEPvLiB3cxrtqfJBSQ264q4GgR3RS8RSvXt36TFN4L'
id = 'origins-test::56ad84f4-21cb-4363-84ba-f6b5a2538191'
uuid = '56ad84f4-21cb-4363-84ba-f6b5a2538191::39c7522a-0cf4-4eae-abe9-49ba89a8b4ed'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmP1ZCiVn6ibdrFdAS4qfz3AFE4mnp7FDcogtVFYD4wKkD'
id = 'freckles-test::b3f758b8-20ac-41b6-902c-d828fab6a5e2'
uuid = 'b3f758b8-20ac-41b6-902c-d828fab6a5e2::39c7522a-0cf4-4eae-abe9-49ba89a8b4ed'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tags/dna/dist/dna.dna.json'
hash = 'QmbqayAkpV2WwJLr7uYMqVYhiZpqeAkLyHGEsu8TMCuaKy'
id = 'tags-test'
uuid = '39c7522a-0cf4-4eae-abe9-49ba89a8b4ed'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/projects/dna/dist/dna.dna.json'
hash = 'QmWF92VRKSFyEtnRqY861UkFL5Uf6PdoTpZi4DU2PPDymQ'
id = 'projects-test'
uuid = '39c7522a-0cf4-4eae-abe9-49ba89a8b4ed'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmRPeM5AFoNCTrTsVnLxPx19zJZnsRDgKjPJmDEpiwA2my'
id = 'origins-test'
uuid = '39c7522a-0cf4-4eae-abe9-49ba89a8b4ed'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmUtmwV5fKS6qSJvrThPYY6sJRbAGw5Mk2rhyvkFdUYJGd'
id = 'origins-test::062649f1-5984-4c63-8f66-83621ce9beea'
uuid = '062649f1-5984-4c63-8f66-83621ce9beea::39c7522a-0cf4-4eae-abe9-49ba89a8b4ed'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmXuZEKjM3ccnnuEZ1Ez2aoDynP2JdZhgVsnrwtugDWJRE'
id = 'kanban-test'
uuid = '39c7522a-0cf4-4eae-abe9-49ba89a8b4ed'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmRQP5SHLhRa86SsnahF3YRN6ExHHU3iLrbAaexEHWMY6t'
id = 'notes-test'
uuid = '39c7522a-0cf4-4eae-abe9-49ba89a8b4ed'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmX2beDouD8so6cXB1v7U5SeAd1ybuJt8kYvjfnVFNiUzJ'
id = 'tasks-test'
uuid = '39c7522a-0cf4-4eae-abe9-49ba89a8b4ed'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmVUbpyRmyu87adPJzLNynEWt8zy4QhNzYn6fcBXdAVrXw'
id = 'fields-test'
uuid = '39c7522a-0cf4-4eae-abe9-49ba89a8b4ed'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmQZojyRAGQDk5ayZNYDbr1e8LRdPW8BVYfQHVKESPJdsj'
id = 'personalinformation-test::6f9e132d-9c93-4f99-8fd7-fcfbccb9bddf'
uuid = '6f9e132d-9c93-4f99-8fd7-fcfbccb9bddf::39c7522a-0cf4-4eae-abe9-49ba89a8b4ed'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmSjH2W2e9mqNjpLZhhAvADHdJtbxGXYknMie8FXwbst72'
id = 'freckles-test::ff492083-c0b0-47f8-8e14-e1131bd651d8'
uuid = 'ff492083-c0b0-47f8-8e14-e1131bd651d8::39c7522a-0cf4-4eae-abe9-49ba89a8b4ed'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmVXLaQkPT4nZ2F4AZQKKqjFCUchwX1ynPZWAFK47K4rUA'
id = 'freckles-test::b4af4ec0-00a2-410a-b84a-96ef35bd9229'
uuid = 'b4af4ec0-00a2-410a-b84a-96ef35bd9229::39c7522a-0cf4-4eae-abe9-49ba89a8b4ed'

[[instances]]
agent = '6261170b-2064-4920-be43-98cc7ca1d68b'
dna = 'origins-test::56ad84f4-21cb-4363-84ba-f6b5a2538191'
id = '6261170b-2064-4920-be43-98cc7ca1d68b'

[instances.storage]
path = '/tmp/tmp.BM8H3lE45C/tryorama/Y5iZxU/6261170b-2064-4920-be43-98cc7ca1d68b'
type = 'lmdb'

[[instances]]
agent = '41553681-4c82-4c8c-87bb-ae2a3d2ba4cc'
dna = 'freckles-test::b3f758b8-20ac-41b6-902c-d828fab6a5e2'
id = '41553681-4c82-4c8c-87bb-ae2a3d2ba4cc'

[instances.storage]
path = '/tmp/tmp.BM8H3lE45C/tryorama/Y5iZxU/41553681-4c82-4c8c-87bb-ae2a3d2ba4cc'
type = 'lmdb'

[[instances]]
agent = '4b7641fe-145d-4217-9768-1e0bff70fdf5'
dna = 'tags-test'
id = '4b7641fe-145d-4217-9768-1e0bff70fdf5'

[instances.storage]
path = '/tmp/tmp.BM8H3lE45C/tryorama/Y5iZxU/4b7641fe-145d-4217-9768-1e0bff70fdf5'
type = 'lmdb'

[[instances]]
agent = 'ef5ba968-0048-4135-b831-a86b615a89b2'
dna = 'projects-test'
id = 'ef5ba968-0048-4135-b831-a86b615a89b2'

[instances.storage]
path = '/tmp/tmp.BM8H3lE45C/tryorama/Y5iZxU/ef5ba968-0048-4135-b831-a86b615a89b2'
type = 'lmdb'

[[instances]]
agent = '57c01ed8-30ae-4fca-b6f9-40192821fed2'
dna = 'origins-test'
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'

[instances.storage]
path = '/tmp/tmp.BM8H3lE45C/tryorama/Y5iZxU/57c01ed8-30ae-4fca-b6f9-40192821fed2'
type = 'lmdb'

[[instances]]
agent = '164449a2-e7d4-47dc-acc8-2fe317b8d9fe'
dna = 'origins-test::062649f1-5984-4c63-8f66-83621ce9beea'
id = '164449a2-e7d4-47dc-acc8-2fe317b8d9fe'

[instances.storage]
path = '/tmp/tmp.BM8H3lE45C/tryorama/Y5iZxU/164449a2-e7d4-47dc-acc8-2fe317b8d9fe'
type = 'lmdb'

[[instances]]
agent = '95569e2e-0de2-4073-8a7d-579f87534c04'
dna = 'kanban-test'
id = '95569e2e-0de2-4073-8a7d-579f87534c04'

[instances.storage]
path = '/tmp/tmp.BM8H3lE45C/tryorama/Y5iZxU/95569e2e-0de2-4073-8a7d-579f87534c04'
type = 'lmdb'

[[instances]]
agent = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'
dna = 'notes-test'
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'

[instances.storage]
path = '/tmp/tmp.BM8H3lE45C/tryorama/Y5iZxU/a23de7fe-bff7-4e6e-87f0-f4c44d038888'
type = 'lmdb'

[[instances]]
agent = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
dna = 'tasks-test'
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'

[instances.storage]
path = '/tmp/tmp.BM8H3lE45C/tryorama/Y5iZxU/e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.BM8H3lE45C/tryorama/Y5iZxU/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::6f9e132d-9c93-4f99-8fd7-fcfbccb9bddf'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.BM8H3lE45C/tryorama/Y5iZxU/personalinformation'
type = 'lmdb'

[[instances]]
agent = '0d765fcf-118f-4122-8f03-f5f9ba74e7fa'
dna = 'freckles-test::ff492083-c0b0-47f8-8e14-e1131bd651d8'
id = '0d765fcf-118f-4122-8f03-f5f9ba74e7fa'

[instances.storage]
path = '/tmp/tmp.BM8H3lE45C/tryorama/Y5iZxU/0d765fcf-118f-4122-8f03-f5f9ba74e7fa'
type = 'lmdb'

[[instances]]
agent = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
dna = 'freckles-test::b4af4ec0-00a2-410a-b84a-96ef35bd9229'
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'

[instances.storage]
path = '/tmp/tmp.BM8H3lE45C/tryorama/Y5iZxU/0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = '6261170b-2064-4920-be43-98cc7ca1d68b'

[[interfaces.instances]]
id = '41553681-4c82-4c8c-87bb-ae2a3d2ba4cc'

[[interfaces.instances]]
id = '4b7641fe-145d-4217-9768-1e0bff70fdf5'

[[interfaces.instances]]
id = 'ef5ba968-0048-4135-b831-a86b615a89b2'

[[interfaces.instances]]
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'

[[interfaces.instances]]
id = '164449a2-e7d4-47dc-acc8-2fe317b8d9fe'

[[interfaces.instances]]
id = '95569e2e-0de2-4073-8a7d-579f87534c04'

[[interfaces.instances]]
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'

[[interfaces.instances]]
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = '0d765fcf-118f-4122-8f03-f5f9ba74e7fa'

[[interfaces.instances]]
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'

[interfaces.driver]
port = 33000
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
