bridges = []
persistence_dir = '/tmp/tmp.BQyMjyicr6/tryorama/fQk5ub'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'c74e9c11-eb79-4459-a187-39ef459a008b'
keystore_file = '[UNUSED]'
name = 'phil::c74e9c11-eb79-4459-a187-39ef459a008b::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'
public_address = 'HcSCieQShoJ3w8qy9vB97kbXDObF9mo3j7EsBjMV9MnaidbcsA7m6gVWcDtvmcz'
test_agent = true

[[agents]]
id = '8239b37b-5b69-43cd-aa2c-28b1054aef20'
keystore_file = '[UNUSED]'
name = 'phil::8239b37b-5b69-43cd-aa2c-28b1054aef20::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'
public_address = 'HcScIVYof7VMddcv7tDkv8nSaMN5ztj8mu74655COEoSnqc9h58yZsagnzitmki'
test_agent = true

[[agents]]
id = '2b3a7e5a-739e-427e-9f38-6992758e0552'
keystore_file = '[UNUSED]'
name = 'phil::2b3a7e5a-739e-427e-9f38-6992758e0552::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'
public_address = 'HcScJZq8PKFEme7txrYPqdC4cIdahbcojj3b6UUPAMc49y6eGaCqiHpQ5g6986a'
test_agent = true

[[agents]]
id = '4b7641fe-145d-4217-9768-1e0bff70fdf5'
keystore_file = '[UNUSED]'
name = 'phil::4b7641fe-145d-4217-9768-1e0bff70fdf5::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'
public_address = 'HcScjt7YoxcJmrinuvYtKGDjdKc7qceaf5iCosd35z96WuuhuOaGCOUPh39hszz'
test_agent = true

[[agents]]
id = 'ef5ba968-0048-4135-b831-a86b615a89b2'
keystore_file = '[UNUSED]'
name = 'phil::ef5ba968-0048-4135-b831-a86b615a89b2::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'
public_address = 'HcScixuMmz4I9s389de7rdt9R4wQHuc779fx3757vOgWAXhiwsycgNrkscwvjpa'
test_agent = true

[[agents]]
id = '01526dbb-17f7-42d4-8a26-01270b50eb73'
keystore_file = '[UNUSED]'
name = 'phil::01526dbb-17f7-42d4-8a26-01270b50eb73::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'
public_address = 'HcSCir5xaVTQyb88pzinR35oc54avMm3m7FuGekbP66nysxh3Ttd9T3m4iKQkuz'
test_agent = true

[[agents]]
id = '15f5c748-e611-47c7-9d1b-7651e5c16d17'
keystore_file = '[UNUSED]'
name = 'phil::15f5c748-e611-47c7-9d1b-7651e5c16d17::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'
public_address = 'HcSCJwpojCr8nzsz7gru9e463c73gaf878JNAQMKXzkdz8kt8EoZ6qJX7Vrcwga'
test_agent = true

[[agents]]
id = '68342fe4-c2e3-4568-836e-421722757c84'
keystore_file = '[UNUSED]'
name = 'phil::68342fe4-c2e3-4568-836e-421722757c84::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'
public_address = 'HcScjkdT4O3P6Jv8xpo6GBjFV6MszqatujF8Fsrab3kwkximypwq3bim3k78kpz'
test_agent = true

[[agents]]
id = '6025b761-26e0-42c2-ad96-8bdc1ce00c33'
keystore_file = '[UNUSED]'
name = 'phil::6025b761-26e0-42c2-ad96-8bdc1ce00c33::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'
public_address = 'HcScIg6fAJ9Repjbz39GMqAyX94PGodr3sI9jS659UIyp4x867Sjs5p6SuJmnpz'
test_agent = true

[[agents]]
id = '1b94be13-632b-4924-aa20-8f67113d7b9a'
keystore_file = '[UNUSED]'
name = 'phil::1b94be13-632b-4924-aa20-8f67113d7b9a::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'
public_address = 'HcSci6HqNYbqx5ik77VTNToy5UQ6sf4sc5k6P3R4qYzSbn46jaxUKmXx4zda4jr'
test_agent = true

[[agents]]
id = '95569e2e-0de2-4073-8a7d-579f87534c04'
keystore_file = '[UNUSED]'
name = 'phil::95569e2e-0de2-4073-8a7d-579f87534c04::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'
public_address = 'HcSciSS3Px4XYovyrx7TdKwORTMwjnsepHmUciUuqrmhrkcbuZVAuM33uQpi6ja'
test_agent = true

[[agents]]
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'
keystore_file = '[UNUSED]'
name = 'phil::a23de7fe-bff7-4e6e-87f0-f4c44d038888::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'
public_address = 'HcSCIrvBZsP7z6zwes89Ar8qo47j3tAVh9CtoNrsyC9xehn3A4f75JqBvCrjcqz'
test_agent = true

[[agents]]
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
keystore_file = '[UNUSED]'
name = 'phil::e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'
public_address = 'HcScj9qG7PHJx8wm9ey7DqvjpqYmk8e88UeH3IfgBVypk34ukU5B38ypPX4E5vz'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'phil::fields::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'
public_address = 'HcScJZx7djKVfa7vmn53ZDTWOjka6m88v3v9z5DDy9aA5xcdR3UN5Czu43YKntz'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'phil::personalinformation::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'
public_address = 'HcScjF3TZwa9Npz553Nmv9fE8sBmj8n6nBhM4yf3366WNRuqcRjYQn5aUhj4hca'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR-Holochain-redux/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmQaBPhdStcYSwKuDDngWHXJ8qfxAoqjcBw41HZv593uvj'
id = 'tasks::8bcc7b22-ade1-4acd-962b-94afc2b19b1a'
uuid = '8bcc7b22-ade1-4acd-962b-94afc2b19b1a::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR-Holochain-redux/dna/notes/dna/dist/dna.dna.json'
hash = 'Qme3WedZZHmzB1Y3voVijEBk2rVXLAgTz3taQipUPasFdL'
id = 'notes::537a9235-3961-4c4c-b279-c9045e85b618'
uuid = '537a9235-3961-4c4c-b279-c9045e85b618::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR-Holochain-redux/dna/tags/dna/dist/dna.dna.json'
hash = 'QmeCwmLbvWM3ajcPMmqaFDRBsGtuX4t1YsJM5DbzWiZMwJ'
id = 'tags::81ac57d9-58cc-4684-b547-3bce7576fba1'
uuid = '81ac57d9-58cc-4684-b547-3bce7576fba1::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR-Holochain-redux/dna/tags/dna/dist/dna.dna.json'
hash = 'QmUC4E2yZQyQQ6UbvSkKG8D6E432SdGHuMULojtMBUDZpi'
id = 'tags::5bf9abe8-a4a9-411e-9dac-d6191a62a87c'
uuid = '5bf9abe8-a4a9-411e-9dac-d6191a62a87c::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR-Holochain-redux/dna/crispr/dna/dist/dna.dna.json'
hash = 'QmTE7xr668Gkc4XMrB3w93qbnVgN9CxAaWAxkWoYsuNL7C'
id = 'projects::277969be-9512-4468-b1ff-b7f958e3c39c'
uuid = '277969be-9512-4468-b1ff-b7f958e3c39c::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR-Holochain-redux/dna/crispr/dna/dist/dna.dna.json'
hash = 'QmatdRSHtfysTeftAPWbDb1eiuEeBPz41hFUHRXA97FFeW'
id = 'projects::51a4a1ce-957d-469e-b3a0-30d2cd7a2fa6'
uuid = '51a4a1ce-957d-469e-b3a0-30d2cd7a2fa6::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR-Holochain-redux/dna/crispr/dna/dist/dna.dna.json'
hash = 'QmeyXXRHyVjTA6K9n2UPijocnGnURU2Jm2Hu7z7SD27egH'
id = 'projects::be907fa8-722d-43ae-8d12-aa983125f4e0'
uuid = 'be907fa8-722d-43ae-8d12-aa983125f4e0::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR-Holochain-redux/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmV2iowXjwYNwKkQ42EAcPie4dB1yZD8tgzFGiMT5uwjR6'
id = 'kanban::493bcb0d-84b8-4894-bdab-c558e5f35f79'
uuid = '493bcb0d-84b8-4894-bdab-c558e5f35f79::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR-Holochain-redux/dna/notes/dna/dist/dna.dna.json'
hash = 'QmZGtKo3h9gEqiYsWpeZFgowyikJACJr8JKAe7MjyNHE2P'
id = 'notes::b1262325-502e-4c68-a2eb-a69f09acbbc5'
uuid = 'b1262325-502e-4c68-a2eb-a69f09acbbc5::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR-Holochain-redux/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmYjKrb8CKrc9md5ueB5vMFEDyNCB3iFqqb5pmSxcHxNze'
id = 'tasks::09298193-6f31-4a8f-9d9a-7d1ea0d49e88'
uuid = '09298193-6f31-4a8f-9d9a-7d1ea0d49e88::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR-Holochain-redux/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmejcBj2Zr2Rog9dAk4xBZKdSVgCZhig1TgiePWh9exam8'
id = 'kanban::d5199a30-2b6e-4756-b6ef-84fc1c5422b1'
uuid = 'd5199a30-2b6e-4756-b6ef-84fc1c5422b1::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR-Holochain-redux/dna/notes/dna/dist/dna.dna.json'
hash = 'QmdJ3DS3g3PZwXZtB4VRNhxwbgHCZQ1GGdxF65LBfjrWjs'
id = 'notes::c78a9590-c57b-4750-9ca2-b73c53a01110'
uuid = 'c78a9590-c57b-4750-9ca2-b73c53a01110::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR-Holochain-redux/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmWjVjtrfovwbJseu72kzLijqpo1yMU3xSjNHetULqVPWe'
id = 'tasks::c48b7988-bccd-431b-b72a-60331fbcedbb'
uuid = 'c48b7988-bccd-431b-b72a-60331fbcedbb::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR-Holochain-redux/dna/curated_fields/dna/dist/dna.dna.json'
hash = 'QmZBy9hXpDEcnr43wV6CrEGb4GhwhpUeBTJ3U2avPCmnX2'
id = 'fields::96960c3f-1036-4e6a-96f1-ef2eebb57f41'
uuid = '96960c3f-1036-4e6a-96f1-ef2eebb57f41::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR-Holochain-redux/dna/personal_information/dna/dist/dna.dna.json'
hash = 'QmSiSSPGthfXFCP4Y6R4C41LoszPKAqCNCEaQiSmWKnibZ'
id = 'personalinformation::9fafb8be-c954-437c-ba07-d0c73c59c2d4'
uuid = '9fafb8be-c954-437c-ba07-d0c73c59c2d4::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'

[[instances]]
agent = 'c74e9c11-eb79-4459-a187-39ef459a008b'
dna = 'tasks::8bcc7b22-ade1-4acd-962b-94afc2b19b1a'
id = 'c74e9c11-eb79-4459-a187-39ef459a008b'

[instances.storage]
path = '/tmp/tmp.BQyMjyicr6/tryorama/fQk5ub/c74e9c11-eb79-4459-a187-39ef459a008b'
type = 'lmdb'

[[instances]]
agent = '8239b37b-5b69-43cd-aa2c-28b1054aef20'
dna = 'notes::537a9235-3961-4c4c-b279-c9045e85b618'
id = '8239b37b-5b69-43cd-aa2c-28b1054aef20'

[instances.storage]
path = '/tmp/tmp.BQyMjyicr6/tryorama/fQk5ub/8239b37b-5b69-43cd-aa2c-28b1054aef20'
type = 'lmdb'

[[instances]]
agent = '2b3a7e5a-739e-427e-9f38-6992758e0552'
dna = 'tags::81ac57d9-58cc-4684-b547-3bce7576fba1'
id = '2b3a7e5a-739e-427e-9f38-6992758e0552'

[instances.storage]
path = '/tmp/tmp.BQyMjyicr6/tryorama/fQk5ub/2b3a7e5a-739e-427e-9f38-6992758e0552'
type = 'lmdb'

[[instances]]
agent = '4b7641fe-145d-4217-9768-1e0bff70fdf5'
dna = 'tags::5bf9abe8-a4a9-411e-9dac-d6191a62a87c'
id = '4b7641fe-145d-4217-9768-1e0bff70fdf5'

[instances.storage]
path = '/tmp/tmp.BQyMjyicr6/tryorama/fQk5ub/4b7641fe-145d-4217-9768-1e0bff70fdf5'
type = 'lmdb'

[[instances]]
agent = 'ef5ba968-0048-4135-b831-a86b615a89b2'
dna = 'projects::277969be-9512-4468-b1ff-b7f958e3c39c'
id = 'ef5ba968-0048-4135-b831-a86b615a89b2'

[instances.storage]
path = '/tmp/tmp.BQyMjyicr6/tryorama/fQk5ub/ef5ba968-0048-4135-b831-a86b615a89b2'
type = 'lmdb'

[[instances]]
agent = '01526dbb-17f7-42d4-8a26-01270b50eb73'
dna = 'projects::51a4a1ce-957d-469e-b3a0-30d2cd7a2fa6'
id = '01526dbb-17f7-42d4-8a26-01270b50eb73'

[instances.storage]
path = '/tmp/tmp.BQyMjyicr6/tryorama/fQk5ub/01526dbb-17f7-42d4-8a26-01270b50eb73'
type = 'lmdb'

[[instances]]
agent = '15f5c748-e611-47c7-9d1b-7651e5c16d17'
dna = 'projects::be907fa8-722d-43ae-8d12-aa983125f4e0'
id = '15f5c748-e611-47c7-9d1b-7651e5c16d17'

[instances.storage]
path = '/tmp/tmp.BQyMjyicr6/tryorama/fQk5ub/15f5c748-e611-47c7-9d1b-7651e5c16d17'
type = 'lmdb'

[[instances]]
agent = '68342fe4-c2e3-4568-836e-421722757c84'
dna = 'kanban::493bcb0d-84b8-4894-bdab-c558e5f35f79'
id = '68342fe4-c2e3-4568-836e-421722757c84'

[instances.storage]
path = '/tmp/tmp.BQyMjyicr6/tryorama/fQk5ub/68342fe4-c2e3-4568-836e-421722757c84'
type = 'lmdb'

[[instances]]
agent = '6025b761-26e0-42c2-ad96-8bdc1ce00c33'
dna = 'notes::b1262325-502e-4c68-a2eb-a69f09acbbc5'
id = '6025b761-26e0-42c2-ad96-8bdc1ce00c33'

[instances.storage]
path = '/tmp/tmp.BQyMjyicr6/tryorama/fQk5ub/6025b761-26e0-42c2-ad96-8bdc1ce00c33'
type = 'lmdb'

[[instances]]
agent = '1b94be13-632b-4924-aa20-8f67113d7b9a'
dna = 'tasks::09298193-6f31-4a8f-9d9a-7d1ea0d49e88'
id = '1b94be13-632b-4924-aa20-8f67113d7b9a'

[instances.storage]
path = '/tmp/tmp.BQyMjyicr6/tryorama/fQk5ub/1b94be13-632b-4924-aa20-8f67113d7b9a'
type = 'lmdb'

[[instances]]
agent = '95569e2e-0de2-4073-8a7d-579f87534c04'
dna = 'kanban::d5199a30-2b6e-4756-b6ef-84fc1c5422b1'
id = '95569e2e-0de2-4073-8a7d-579f87534c04'

[instances.storage]
path = '/tmp/tmp.BQyMjyicr6/tryorama/fQk5ub/95569e2e-0de2-4073-8a7d-579f87534c04'
type = 'lmdb'

[[instances]]
agent = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'
dna = 'notes::c78a9590-c57b-4750-9ca2-b73c53a01110'
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'

[instances.storage]
path = '/tmp/tmp.BQyMjyicr6/tryorama/fQk5ub/a23de7fe-bff7-4e6e-87f0-f4c44d038888'
type = 'lmdb'

[[instances]]
agent = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
dna = 'tasks::c48b7988-bccd-431b-b72a-60331fbcedbb'
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'

[instances.storage]
path = '/tmp/tmp.BQyMjyicr6/tryorama/fQk5ub/e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields::96960c3f-1036-4e6a-96f1-ef2eebb57f41'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.BQyMjyicr6/tryorama/fQk5ub/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation::9fafb8be-c954-437c-ba07-d0c73c59c2d4'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.BQyMjyicr6/tryorama/fQk5ub/personalinformation'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'developer-interface'

[[interfaces.instances]]
id = 'c74e9c11-eb79-4459-a187-39ef459a008b'

[[interfaces.instances]]
id = '8239b37b-5b69-43cd-aa2c-28b1054aef20'

[[interfaces.instances]]
id = '2b3a7e5a-739e-427e-9f38-6992758e0552'

[[interfaces.instances]]
id = '4b7641fe-145d-4217-9768-1e0bff70fdf5'

[[interfaces.instances]]
id = 'ef5ba968-0048-4135-b831-a86b615a89b2'

[[interfaces.instances]]
id = '01526dbb-17f7-42d4-8a26-01270b50eb73'

[[interfaces.instances]]
id = '15f5c748-e611-47c7-9d1b-7651e5c16d17'

[[interfaces.instances]]
id = '68342fe4-c2e3-4568-836e-421722757c84'

[[interfaces.instances]]
id = '6025b761-26e0-42c2-ad96-8bdc1ce00c33'

[[interfaces.instances]]
id = '1b94be13-632b-4924-aa20-8f67113d7b9a'

[[interfaces.instances]]
id = '95569e2e-0de2-4073-8a7d-579f87534c04'

[[interfaces.instances]]
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'

[[interfaces.instances]]
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[interfaces.driver]
port = 43000
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
