persistence_dir = "/tmp/tmp.LFoyV7RAql/tryorama/VG6n0X"

[[agents]]
name = "phil::c74e9c11-eb79-4459-a187-39ef459a008b::8fee2803-55c8-4ffd-9f2b-029bab84aadb"
id = "c74e9c11-eb79-4459-a187-39ef459a008b"
keystore_file = "[UNUSED]"
public_address = "[SHOULD BE REWRITTEN]"
test_agent = true

[[agents]]
name = "phil::8239b37b-5b69-43cd-aa2c-28b1054aef20::8fee2803-55c8-4ffd-9f2b-029bab84aadb"
id = "8239b37b-5b69-43cd-aa2c-28b1054aef20"
keystore_file = "[UNUSED]"
public_address = "[SHOULD BE REWRITTEN]"
test_agent = true

[[agents]]
name = "phil::6261170b-2064-4920-be43-98cc7ca1d68b::8fee2803-55c8-4ffd-9f2b-029bab84aadb"
id = "6261170b-2064-4920-be43-98cc7ca1d68b"
keystore_file = "[UNUSED]"
public_address = "[SHOULD BE REWRITTEN]"
test_agent = true

[[agents]]
name = "phil::2b3a7e5a-739e-427e-9f38-6992758e0552::8fee2803-55c8-4ffd-9f2b-029bab84aadb"
id = "2b3a7e5a-739e-427e-9f38-6992758e0552"
keystore_file = "[UNUSED]"
public_address = "[SHOULD BE REWRITTEN]"
test_agent = true

[[agents]]
name = "phil::4b7641fe-145d-4217-9768-1e0bff70fdf5::8fee2803-55c8-4ffd-9f2b-029bab84aadb"
id = "4b7641fe-145d-4217-9768-1e0bff70fdf5"
keystore_file = "[UNUSED]"
public_address = "[SHOULD BE REWRITTEN]"
test_agent = true

[[agents]]
name = "phil::ef5ba968-0048-4135-b831-a86b615a89b2::8fee2803-55c8-4ffd-9f2b-029bab84aadb"
id = "ef5ba968-0048-4135-b831-a86b615a89b2"
keystore_file = "[UNUSED]"
public_address = "[SHOULD BE REWRITTEN]"
test_agent = true

[[agents]]
name = "phil::01526dbb-17f7-42d4-8a26-01270b50eb73::8fee2803-55c8-4ffd-9f2b-029bab84aadb"
id = "01526dbb-17f7-42d4-8a26-01270b50eb73"
keystore_file = "[UNUSED]"
public_address = "[SHOULD BE REWRITTEN]"
test_agent = true

[[agents]]
name = "phil::15f5c748-e611-47c7-9d1b-7651e5c16d17::8fee2803-55c8-4ffd-9f2b-029bab84aadb"
id = "15f5c748-e611-47c7-9d1b-7651e5c16d17"
keystore_file = "[UNUSED]"
public_address = "[SHOULD BE REWRITTEN]"
test_agent = true

[[agents]]
name = "phil::68342fe4-c2e3-4568-836e-421722757c84::8fee2803-55c8-4ffd-9f2b-029bab84aadb"
id = "68342fe4-c2e3-4568-836e-421722757c84"
keystore_file = "[UNUSED]"
public_address = "[SHOULD BE REWRITTEN]"
test_agent = true

[[agents]]
name = "phil::6025b761-26e0-42c2-ad96-8bdc1ce00c33::8fee2803-55c8-4ffd-9f2b-029bab84aadb"
id = "6025b761-26e0-42c2-ad96-8bdc1ce00c33"
keystore_file = "[UNUSED]"
public_address = "[SHOULD BE REWRITTEN]"
test_agent = true

[[agents]]
name = "phil::1b94be13-632b-4924-aa20-8f67113d7b9a::8fee2803-55c8-4ffd-9f2b-029bab84aadb"
id = "1b94be13-632b-4924-aa20-8f67113d7b9a"
keystore_file = "[UNUSED]"
public_address = "[SHOULD BE REWRITTEN]"
test_agent = true

[[agents]]
name = "phil::57c01ed8-30ae-4fca-b6f9-40192821fed2::8fee2803-55c8-4ffd-9f2b-029bab84aadb"
id = "57c01ed8-30ae-4fca-b6f9-40192821fed2"
keystore_file = "[UNUSED]"
public_address = "[SHOULD BE REWRITTEN]"
test_agent = true

[[agents]]
name = "phil::164449a2-e7d4-47dc-acc8-2fe317b8d9fe::8fee2803-55c8-4ffd-9f2b-029bab84aadb"
id = "164449a2-e7d4-47dc-acc8-2fe317b8d9fe"
keystore_file = "[UNUSED]"
public_address = "[SHOULD BE REWRITTEN]"
test_agent = true

[[agents]]
name = "phil::95569e2e-0de2-4073-8a7d-579f87534c04::8fee2803-55c8-4ffd-9f2b-029bab84aadb"
id = "95569e2e-0de2-4073-8a7d-579f87534c04"
keystore_file = "[UNUSED]"
public_address = "[SHOULD BE REWRITTEN]"
test_agent = true

[[agents]]
name = "phil::a23de7fe-bff7-4e6e-87f0-f4c44d038888::8fee2803-55c8-4ffd-9f2b-029bab84aadb"
id = "a23de7fe-bff7-4e6e-87f0-f4c44d038888"
keystore_file = "[UNUSED]"
public_address = "[SHOULD BE REWRITTEN]"
test_agent = true

[[agents]]
name = "phil::e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a::8fee2803-55c8-4ffd-9f2b-029bab84aadb"
id = "e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a"
keystore_file = "[UNUSED]"
public_address = "[SHOULD BE REWRITTEN]"
test_agent = true

[[agents]]
name = "phil::fields::8fee2803-55c8-4ffd-9f2b-029bab84aadb"
id = "fields"
keystore_file = "[UNUSED]"
public_address = "[SHOULD BE REWRITTEN]"
test_agent = true

[[agents]]
name = "phil::personalinformation::8fee2803-55c8-4ffd-9f2b-029bab84aadb"
id = "personalinformation"
keystore_file = "[UNUSED]"
public_address = "[SHOULD BE REWRITTEN]"
test_agent = true

[[dnas]]
file = "/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json"
id = "tasks::f74b6356-eaa3-4ec9-bf25-22aa344adc57"
uuid = "f74b6356-eaa3-4ec9-bf25-22aa344adc57::8fee2803-55c8-4ffd-9f2b-029bab84aadb"
hash = "QmZgv4NoGLbxrChNofgX6PXfdX7QP3AfSS1tm7CggKJUr3"

[[dnas]]
file = "/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json"
id = "notes::fc111792-21a2-43ce-a38f-5674adc54452"
uuid = "fc111792-21a2-43ce-a38f-5674adc54452::8fee2803-55c8-4ffd-9f2b-029bab84aadb"
hash = "Qmf3YMQnFaRm7UTzm7J9v3bhW3jbM76FW38iYTGQZUfLmf"

[[dnas]]
file = "/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json"
id = "origins::ac0a7a57-f07a-45a7-a449-a6b9c17fe6d6"
uuid = "ac0a7a57-f07a-45a7-a449-a6b9c17fe6d6::8fee2803-55c8-4ffd-9f2b-029bab84aadb"
hash = "[UNKNOWN]"

[[dnas]]
file = "/Users/philipbeadle/holochain/CRISPR/dna/tags/dna/dist/dna.dna.json"
id = "tags::4944d858-0f15-4546-9670-6a3f932298e6"
uuid = "4944d858-0f15-4546-9670-6a3f932298e6::8fee2803-55c8-4ffd-9f2b-029bab84aadb"
hash = "QmegStqxHD4eVnyutQk6KSCvvAfRgSujgELLonKJYzMDG1"

[[dnas]]
file = "/Users/philipbeadle/holochain/CRISPR/dna/tags/dna/dist/dna.dna.json"
id = "tags::250d0c7b-4e24-489d-9fa6-391c5a83b878"
uuid = "250d0c7b-4e24-489d-9fa6-391c5a83b878::8fee2803-55c8-4ffd-9f2b-029bab84aadb"
hash = "QmegStqxHD4eVnyutQk6KSCvvAfRgSujgELLonKJYzMDG1"

[[dnas]]
file = "/Users/philipbeadle/holochain/CRISPR/dna/projects/dna/dist/dna.dna.json"
id = "projects::0104505e-4ac0-4732-9910-55424ab05773"
uuid = "0104505e-4ac0-4732-9910-55424ab05773::8fee2803-55c8-4ffd-9f2b-029bab84aadb"
hash = "[UNKNOWN]"

[[dnas]]
file = "/Users/philipbeadle/holochain/CRISPR/dna/projects/dna/dist/dna.dna.json"
id = "projects::fbab017a-8634-4b1e-94ea-7978430ff4e0"
uuid = "fbab017a-8634-4b1e-94ea-7978430ff4e0::8fee2803-55c8-4ffd-9f2b-029bab84aadb"
hash = "[UNKNOWN]"

[[dnas]]
file = "/Users/philipbeadle/holochain/CRISPR/dna/projects/dna/dist/dna.dna.json"
id = "projects::bbe450ee-5a44-4fbe-ab08-3ec815666151"
uuid = "bbe450ee-5a44-4fbe-ab08-3ec815666151::8fee2803-55c8-4ffd-9f2b-029bab84aadb"
hash = "[UNKNOWN]"

[[dnas]]
file = "/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json"
id = "kanban::cb213d72-5cf0-4230-b6f2-51688d4b2546"
uuid = "cb213d72-5cf0-4230-b6f2-51688d4b2546::8fee2803-55c8-4ffd-9f2b-029bab84aadb"
hash = "Qmbw6ozbLWY6AJzfihEEVxDnANYhxTdzkZ8vHKzxm7iNQq"

[[dnas]]
file = "/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json"
id = "notes::362345fa-f6f5-4b2f-83e2-0e48a0f19443"
uuid = "362345fa-f6f5-4b2f-83e2-0e48a0f19443::8fee2803-55c8-4ffd-9f2b-029bab84aadb"
hash = "Qmf3YMQnFaRm7UTzm7J9v3bhW3jbM76FW38iYTGQZUfLmf"

[[dnas]]
file = "/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json"
id = "tasks::a6c8bf5f-6352-41b5-bf86-c292dc340305"
uuid = "a6c8bf5f-6352-41b5-bf86-c292dc340305::8fee2803-55c8-4ffd-9f2b-029bab84aadb"
hash = "QmZgv4NoGLbxrChNofgX6PXfdX7QP3AfSS1tm7CggKJUr3"

[[dnas]]
file = "/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json"
id = "origins::7fcf138b-2ed5-4fdc-b813-a853888f8b43"
uuid = "7fcf138b-2ed5-4fdc-b813-a853888f8b43::8fee2803-55c8-4ffd-9f2b-029bab84aadb"
hash = "[UNKNOWN]"

[[dnas]]
file = "/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json"
id = "origins::cbc8cf8d-86d6-42e4-9f77-647f6741deda"
uuid = "cbc8cf8d-86d6-42e4-9f77-647f6741deda::8fee2803-55c8-4ffd-9f2b-029bab84aadb"
hash = "[UNKNOWN]"

[[dnas]]
file = "/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json"
id = "kanban::aff8a76a-23e7-438b-b911-f6e2e037e64c"
uuid = "aff8a76a-23e7-438b-b911-f6e2e037e64c::8fee2803-55c8-4ffd-9f2b-029bab84aadb"
hash = "Qmbw6ozbLWY6AJzfihEEVxDnANYhxTdzkZ8vHKzxm7iNQq"

[[dnas]]
file = "/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json"
id = "notes::ea6373e2-de9e-4318-870f-854f9a8ceff8"
uuid = "ea6373e2-de9e-4318-870f-854f9a8ceff8::8fee2803-55c8-4ffd-9f2b-029bab84aadb"
hash = "Qmf3YMQnFaRm7UTzm7J9v3bhW3jbM76FW38iYTGQZUfLmf"

[[dnas]]
file = "/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json"
id = "tasks::12b06e5e-cc32-4fbd-b512-09cfbebdcb7e"
uuid = "12b06e5e-cc32-4fbd-b512-09cfbebdcb7e::8fee2803-55c8-4ffd-9f2b-029bab84aadb"
hash = "QmZgv4NoGLbxrChNofgX6PXfdX7QP3AfSS1tm7CggKJUr3"

[[dnas]]
file = "/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json"
id = "fields::c8a383d5-b738-4480-8088-4facddbcc782"
uuid = "c8a383d5-b738-4480-8088-4facddbcc782::8fee2803-55c8-4ffd-9f2b-029bab84aadb"
hash = "[UNKNOWN]"

[[dnas]]
file = "/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json"
id = "personalinformation::241785da-a2af-4484-8a60-e71fa54890c6"
uuid = "241785da-a2af-4484-8a60-e71fa54890c6::8fee2803-55c8-4ffd-9f2b-029bab84aadb"
hash = "[UNKNOWN]"

[[instances]]
id = "c74e9c11-eb79-4459-a187-39ef459a008b"
agent = "c74e9c11-eb79-4459-a187-39ef459a008b"
dna = "tasks::f74b6356-eaa3-4ec9-bf25-22aa344adc57"

  [instances.storage]
  type = "lmdb"
  path = "/tmp/tmp.LFoyV7RAql/tryorama/VG6n0X/c74e9c11-eb79-4459-a187-39ef459a008b"

[[instances]]
id = "8239b37b-5b69-43cd-aa2c-28b1054aef20"
agent = "8239b37b-5b69-43cd-aa2c-28b1054aef20"
dna = "notes::fc111792-21a2-43ce-a38f-5674adc54452"

  [instances.storage]
  type = "lmdb"
  path = "/tmp/tmp.LFoyV7RAql/tryorama/VG6n0X/8239b37b-5b69-43cd-aa2c-28b1054aef20"

[[instances]]
id = "6261170b-2064-4920-be43-98cc7ca1d68b"
agent = "6261170b-2064-4920-be43-98cc7ca1d68b"
dna = "origins::ac0a7a57-f07a-45a7-a449-a6b9c17fe6d6"

  [instances.storage]
  type = "lmdb"
  path = "/tmp/tmp.LFoyV7RAql/tryorama/VG6n0X/6261170b-2064-4920-be43-98cc7ca1d68b"

[[instances]]
id = "2b3a7e5a-739e-427e-9f38-6992758e0552"
agent = "2b3a7e5a-739e-427e-9f38-6992758e0552"
dna = "tags::4944d858-0f15-4546-9670-6a3f932298e6"

  [instances.storage]
  type = "lmdb"
  path = "/tmp/tmp.LFoyV7RAql/tryorama/VG6n0X/2b3a7e5a-739e-427e-9f38-6992758e0552"

[[instances]]
id = "4b7641fe-145d-4217-9768-1e0bff70fdf5"
agent = "4b7641fe-145d-4217-9768-1e0bff70fdf5"
dna = "tags::250d0c7b-4e24-489d-9fa6-391c5a83b878"

  [instances.storage]
  type = "lmdb"
  path = "/tmp/tmp.LFoyV7RAql/tryorama/VG6n0X/4b7641fe-145d-4217-9768-1e0bff70fdf5"

[[instances]]
id = "ef5ba968-0048-4135-b831-a86b615a89b2"
agent = "ef5ba968-0048-4135-b831-a86b615a89b2"
dna = "projects::0104505e-4ac0-4732-9910-55424ab05773"

  [instances.storage]
  type = "lmdb"
  path = "/tmp/tmp.LFoyV7RAql/tryorama/VG6n0X/ef5ba968-0048-4135-b831-a86b615a89b2"

[[instances]]
id = "01526dbb-17f7-42d4-8a26-01270b50eb73"
agent = "01526dbb-17f7-42d4-8a26-01270b50eb73"
dna = "projects::fbab017a-8634-4b1e-94ea-7978430ff4e0"

  [instances.storage]
  type = "lmdb"
  path = "/tmp/tmp.LFoyV7RAql/tryorama/VG6n0X/01526dbb-17f7-42d4-8a26-01270b50eb73"

[[instances]]
id = "15f5c748-e611-47c7-9d1b-7651e5c16d17"
agent = "15f5c748-e611-47c7-9d1b-7651e5c16d17"
dna = "projects::bbe450ee-5a44-4fbe-ab08-3ec815666151"

  [instances.storage]
  type = "lmdb"
  path = "/tmp/tmp.LFoyV7RAql/tryorama/VG6n0X/15f5c748-e611-47c7-9d1b-7651e5c16d17"

[[instances]]
id = "68342fe4-c2e3-4568-836e-421722757c84"
agent = "68342fe4-c2e3-4568-836e-421722757c84"
dna = "kanban::cb213d72-5cf0-4230-b6f2-51688d4b2546"

  [instances.storage]
  type = "lmdb"
  path = "/tmp/tmp.LFoyV7RAql/tryorama/VG6n0X/68342fe4-c2e3-4568-836e-421722757c84"

[[instances]]
id = "6025b761-26e0-42c2-ad96-8bdc1ce00c33"
agent = "6025b761-26e0-42c2-ad96-8bdc1ce00c33"
dna = "notes::362345fa-f6f5-4b2f-83e2-0e48a0f19443"

  [instances.storage]
  type = "lmdb"
  path = "/tmp/tmp.LFoyV7RAql/tryorama/VG6n0X/6025b761-26e0-42c2-ad96-8bdc1ce00c33"

[[instances]]
id = "1b94be13-632b-4924-aa20-8f67113d7b9a"
agent = "1b94be13-632b-4924-aa20-8f67113d7b9a"
dna = "tasks::a6c8bf5f-6352-41b5-bf86-c292dc340305"

  [instances.storage]
  type = "lmdb"
  path = "/tmp/tmp.LFoyV7RAql/tryorama/VG6n0X/1b94be13-632b-4924-aa20-8f67113d7b9a"

[[instances]]
id = "57c01ed8-30ae-4fca-b6f9-40192821fed2"
agent = "57c01ed8-30ae-4fca-b6f9-40192821fed2"
dna = "origins::7fcf138b-2ed5-4fdc-b813-a853888f8b43"

  [instances.storage]
  type = "lmdb"
  path = "/tmp/tmp.LFoyV7RAql/tryorama/VG6n0X/57c01ed8-30ae-4fca-b6f9-40192821fed2"

[[instances]]
id = "164449a2-e7d4-47dc-acc8-2fe317b8d9fe"
agent = "164449a2-e7d4-47dc-acc8-2fe317b8d9fe"
dna = "origins::cbc8cf8d-86d6-42e4-9f77-647f6741deda"

  [instances.storage]
  type = "lmdb"
  path = "/tmp/tmp.LFoyV7RAql/tryorama/VG6n0X/164449a2-e7d4-47dc-acc8-2fe317b8d9fe"

[[instances]]
id = "95569e2e-0de2-4073-8a7d-579f87534c04"
agent = "95569e2e-0de2-4073-8a7d-579f87534c04"
dna = "kanban::aff8a76a-23e7-438b-b911-f6e2e037e64c"

  [instances.storage]
  type = "lmdb"
  path = "/tmp/tmp.LFoyV7RAql/tryorama/VG6n0X/95569e2e-0de2-4073-8a7d-579f87534c04"

[[instances]]
id = "a23de7fe-bff7-4e6e-87f0-f4c44d038888"
agent = "a23de7fe-bff7-4e6e-87f0-f4c44d038888"
dna = "notes::ea6373e2-de9e-4318-870f-854f9a8ceff8"

  [instances.storage]
  type = "lmdb"
  path = "/tmp/tmp.LFoyV7RAql/tryorama/VG6n0X/a23de7fe-bff7-4e6e-87f0-f4c44d038888"

[[instances]]
id = "e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a"
agent = "e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a"
dna = "tasks::12b06e5e-cc32-4fbd-b512-09cfbebdcb7e"

  [instances.storage]
  type = "lmdb"
  path = "/tmp/tmp.LFoyV7RAql/tryorama/VG6n0X/e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a"

[[instances]]
id = "fields"
agent = "fields"
dna = "fields::c8a383d5-b738-4480-8088-4facddbcc782"

  [instances.storage]
  type = "lmdb"
  path = "/tmp/tmp.LFoyV7RAql/tryorama/VG6n0X/fields"

[[instances]]
id = "personalinformation"
agent = "personalinformation"
dna = "personalinformation::241785da-a2af-4484-8a60-e71fa54890c6"

  [instances.storage]
  type = "lmdb"
  path = "/tmp/tmp.LFoyV7RAql/tryorama/VG6n0X/personalinformation"

[[interfaces]]
admin = true
choose_free_port = false
id = "tryorama-interface"

  [interfaces.driver]
  type = "websocket"
  port = 33_000

  [[interfaces.instances]]
  id = "c74e9c11-eb79-4459-a187-39ef459a008b"

  [[interfaces.instances]]
  id = "8239b37b-5b69-43cd-aa2c-28b1054aef20"

  [[interfaces.instances]]
  id = "6261170b-2064-4920-be43-98cc7ca1d68b"

  [[interfaces.instances]]
  id = "2b3a7e5a-739e-427e-9f38-6992758e0552"

  [[interfaces.instances]]
  id = "4b7641fe-145d-4217-9768-1e0bff70fdf5"

  [[interfaces.instances]]
  id = "ef5ba968-0048-4135-b831-a86b615a89b2"

  [[interfaces.instances]]
  id = "01526dbb-17f7-42d4-8a26-01270b50eb73"

  [[interfaces.instances]]
  id = "15f5c748-e611-47c7-9d1b-7651e5c16d17"

  [[interfaces.instances]]
  id = "68342fe4-c2e3-4568-836e-421722757c84"

  [[interfaces.instances]]
  id = "6025b761-26e0-42c2-ad96-8bdc1ce00c33"

  [[interfaces.instances]]
  id = "1b94be13-632b-4924-aa20-8f67113d7b9a"

  [[interfaces.instances]]
  id = "57c01ed8-30ae-4fca-b6f9-40192821fed2"

  [[interfaces.instances]]
  id = "164449a2-e7d4-47dc-acc8-2fe317b8d9fe"

  [[interfaces.instances]]
  id = "95569e2e-0de2-4073-8a7d-579f87534c04"

  [[interfaces.instances]]
  id = "a23de7fe-bff7-4e6e-87f0-f4c44d038888"

  [[interfaces.instances]]
  id = "e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a"

  [[interfaces.instances]]
  id = "fields"

  [[interfaces.instances]]
  id = "personalinformation"

[signals]
trace = false
consistency = true

[network]
type = "sim2h"
sim2h_url = "ws://localhost:9000"

[logger]
type = "error"
state_dump = true

[[logger.rules.rules]]
exclude = true
pattern = ".*parity.*"

[[logger.rules.rules]]
exclude = true
pattern = ".*mio.*"

[[logger.rules.rules]]
exclude = true
pattern = ".*tokio.*"

[[logger.rules.rules]]
exclude = true
pattern = ".*hyper.*"

[[logger.rules.rules]]
exclude = true
pattern = ".*rusoto_core.*"

[[logger.rules.rules]]
exclude = true
pattern = ".*want.*"

[[logger.rules.rules]]
exclude = true
pattern = ".*rpc.*"
