bridges = []
persistence_dir = '/tmp/tmp.LFoyV7RAql/tryorama/dq1pcd'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = '6261170b-2064-4920-be43-98cc7ca1d68b'
keystore_file = '[UNUSED]'
name = 'phil::6261170b-2064-4920-be43-98cc7ca1d68b::eb9f8e91-f383-4575-a549-e0b4bb52042e'
public_address = 'HcSCjPwOJM9q9nc4ctAkamOAFOnfsqgabEXfnRQ6qKbzqojizbAoST538gi6f9i'
test_agent = true

[[agents]]
id = '4b7641fe-145d-4217-9768-1e0bff70fdf5'
keystore_file = '[UNUSED]'
name = 'phil::4b7641fe-145d-4217-9768-1e0bff70fdf5::eb9f8e91-f383-4575-a549-e0b4bb52042e'
public_address = 'HcSCjUSsG49Gwg95e3PQ5Cg3OwyTydxm89e73aSpkT4jWfu9fkSgYsKXfr38orr'
test_agent = true

[[agents]]
id = 'ef5ba968-0048-4135-b831-a86b615a89b2'
keystore_file = '[UNUSED]'
name = 'phil::ef5ba968-0048-4135-b831-a86b615a89b2::eb9f8e91-f383-4575-a549-e0b4bb52042e'
public_address = 'HcScJ7WHtfSngrrtroeuA3WJIBA668xpp8VVMRWP5C7365irFTV4r84w68Cavoi'
test_agent = true

[[agents]]
id = '01526dbb-17f7-42d4-8a26-01270b50eb73'
keystore_file = '[UNUSED]'
name = 'phil::01526dbb-17f7-42d4-8a26-01270b50eb73::eb9f8e91-f383-4575-a549-e0b4bb52042e'
public_address = 'HcSCIJYbOSNq5uiqnnUZcYxjjRa75n3d4bX77krT54w9kNdx7m8X79DC4tBtTaa'
test_agent = true

[[agents]]
id = '15f5c748-e611-47c7-9d1b-7651e5c16d17'
keystore_file = '[UNUSED]'
name = 'phil::15f5c748-e611-47c7-9d1b-7651e5c16d17::eb9f8e91-f383-4575-a549-e0b4bb52042e'
public_address = 'HcSCJZ9zufYWzg4xmjeIzqqw39Q83Jbpfe5EZIizxRafum5wq3Uuikoxe9o53zr'
test_agent = true

[[agents]]
id = '68342fe4-c2e3-4568-836e-421722757c84'
keystore_file = '[UNUSED]'
name = 'phil::68342fe4-c2e3-4568-836e-421722757c84::eb9f8e91-f383-4575-a549-e0b4bb52042e'
public_address = 'HcScJ4Y7TZXpj96eidmdyaDab3fpex9saXhzKRENKakusib6OE3dUKD3mvttuba'
test_agent = true

[[agents]]
id = '6025b761-26e0-42c2-ad96-8bdc1ce00c33'
keystore_file = '[UNUSED]'
name = 'phil::6025b761-26e0-42c2-ad96-8bdc1ce00c33::eb9f8e91-f383-4575-a549-e0b4bb52042e'
public_address = 'HcSCIrQjGV6K4d7cemCdSV4iCNTeitwdtqvaJYRDK8mtbijysZb89Jakqavh6zz'
test_agent = true

[[agents]]
id = '1b94be13-632b-4924-aa20-8f67113d7b9a'
keystore_file = '[UNUSED]'
name = 'phil::1b94be13-632b-4924-aa20-8f67113d7b9a::eb9f8e91-f383-4575-a549-e0b4bb52042e'
public_address = 'HcSCitrCY4JQ49dinu8SF6D3AVDKXuho5vSCeyq3dhr3rzgjKjeqjRYQaksneaa'
test_agent = true

[[agents]]
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'
keystore_file = '[UNUSED]'
name = 'phil::57c01ed8-30ae-4fca-b6f9-40192821fed2::eb9f8e91-f383-4575-a549-e0b4bb52042e'
public_address = 'HcScjAae5Xn8D66b88ehn6Ix3s67Z4sz8WkptViWmosx4h9fBxeG95a788OOria'
test_agent = true

[[agents]]
id = '164449a2-e7d4-47dc-acc8-2fe317b8d9fe'
keystore_file = '[UNUSED]'
name = 'phil::164449a2-e7d4-47dc-acc8-2fe317b8d9fe::eb9f8e91-f383-4575-a549-e0b4bb52042e'
public_address = 'HcSCIHPC4eK4hq9v73jvw7uY6Oqrkmeozu44945KvCNhfoxa7ir557tirtpFher'
test_agent = true

[[agents]]
id = '95569e2e-0de2-4073-8a7d-579f87534c04'
keystore_file = '[UNUSED]'
name = 'phil::95569e2e-0de2-4073-8a7d-579f87534c04::eb9f8e91-f383-4575-a549-e0b4bb52042e'
public_address = 'HcSciakXb4qGimzvepP9tzKj95MwxizsmWpTIT8JE5Xnh3u3zMOgKP8MTvmjewr'
test_agent = true

[[agents]]
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'
keystore_file = '[UNUSED]'
name = 'phil::a23de7fe-bff7-4e6e-87f0-f4c44d038888::eb9f8e91-f383-4575-a549-e0b4bb52042e'
public_address = 'HcScIAYkxeIndbry4dWnIVQQCy7dnmaue4cQymwhVo9zs4tapIcN7nKVjrs8aga'
test_agent = true

[[agents]]
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
keystore_file = '[UNUSED]'
name = 'phil::e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a::eb9f8e91-f383-4575-a549-e0b4bb52042e'
public_address = 'HcSci3Mee8qwNtnc49Q5A4yNk68y53DAuwAN7oYJff9jj88rVfiU9nrIZxxihqz'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'phil::fields::eb9f8e91-f383-4575-a549-e0b4bb52042e'
public_address = 'HcScIVpgUG3r5agwfdhiz7OpOBeeh8vygzcG5g6pXUs5tt8nb7e8W6UOyQDqfka'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'phil::personalinformation::eb9f8e91-f383-4575-a549-e0b4bb52042e'
public_address = 'HcSCjHGdDPSv9ep5oveA3Nnf4xFN4ccccS55Wkek35cvUw4gzk3G983ezScHxsa'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmZ7uNpYEkgspcmYCYq5i5HqFQHrgYbi9CCVQo75mMaWC9'
id = 'origins::9f713c88-ba83-49a5-9222-e47b29e00327'
uuid = '9f713c88-ba83-49a5-9222-e47b29e00327::eb9f8e91-f383-4575-a549-e0b4bb52042e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tags/dna/dist/dna.dna.json'
hash = 'QmNmLso8CNpAvtLj62jW8i8unB3rq7daYgUHScCyYPHWyC'
id = 'tags::b524ebf4-f59c-40e4-8849-5fc719ca6742'
uuid = 'b524ebf4-f59c-40e4-8849-5fc719ca6742::eb9f8e91-f383-4575-a549-e0b4bb52042e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/projects/dna/dist/dna.dna.json'
hash = 'QmaSPmbr8g3EXBMf4Lwudx53ZB94kPZ7u65PPPLZQn5XB6'
id = 'projects::1b16f44c-8b73-405f-bbbc-19a93162f443'
uuid = '1b16f44c-8b73-405f-bbbc-19a93162f443::eb9f8e91-f383-4575-a549-e0b4bb52042e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/projects/dna/dist/dna.dna.json'
hash = 'Qma1dk2ScCAhfcJ3ntzXYu2q74xDCtzyCtAK8MtGELSLkR'
id = 'projects::9eb3f03d-7dea-4dfc-a54a-45faa01e92d2'
uuid = '9eb3f03d-7dea-4dfc-a54a-45faa01e92d2::eb9f8e91-f383-4575-a549-e0b4bb52042e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/projects/dna/dist/dna.dna.json'
hash = 'QmQ6ds3u3gSXGh2qsFajSDM6WNAETgegD1rjwhMu1yPFTg'
id = 'projects::e61e0bbd-f9a6-4e03-960a-4ff555e28c20'
uuid = 'e61e0bbd-f9a6-4e03-960a-4ff555e28c20::eb9f8e91-f383-4575-a549-e0b4bb52042e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmdTjVVVPCxnViWL58xZwjpxSyTTG8gp1kQ2VDmQGDQrNH'
id = 'kanban::1b3cdb13-3a60-4f9e-b473-44ab68d510b6'
uuid = '1b3cdb13-3a60-4f9e-b473-44ab68d510b6::eb9f8e91-f383-4575-a549-e0b4bb52042e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmTcgf8dmNmdzGzPa8y7cpWHaQ34SCg2crRWyKurdQkbVm'
id = 'notes::da68efe4-53ee-45e6-9f72-999c364a39cf'
uuid = 'da68efe4-53ee-45e6-9f72-999c364a39cf::eb9f8e91-f383-4575-a549-e0b4bb52042e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmbJSMWUH8PGWqsGtqxSyDsFWj9Ao36ZReRBQhh5TRWBas'
id = 'tasks::c74b5f26-755a-4b96-977c-240e3074db73'
uuid = 'c74b5f26-755a-4b96-977c-240e3074db73::eb9f8e91-f383-4575-a549-e0b4bb52042e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmTkKwEf7e3X3Pdgxyup5zrhWrZ7huwKqARTygApyGmN5G'
id = 'origins::fb20018f-4dc8-49c9-9fcd-9ab1bbf27fb0'
uuid = 'fb20018f-4dc8-49c9-9fcd-9ab1bbf27fb0::eb9f8e91-f383-4575-a549-e0b4bb52042e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmT7waunRi6AAJKyBTcuy2T3Fuig7jayVqhKJeJxZW8VT2'
id = 'origins::73e6e83e-b352-479d-bc18-287d2bd13e81'
uuid = '73e6e83e-b352-479d-bc18-287d2bd13e81::eb9f8e91-f383-4575-a549-e0b4bb52042e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmYz3SoumhYTzajADe6VFJs1VVnsTdFfC8MokThhiw6o8U'
id = 'kanban::885ec18a-b1f0-434b-98cf-0ae143bd0506'
uuid = '885ec18a-b1f0-434b-98cf-0ae143bd0506::eb9f8e91-f383-4575-a549-e0b4bb52042e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmXt2oGMcG1LCdRJdg61Gu94z1TUgsgALyPEM2A6CrmcES'
id = 'notes::8af2cdb4-cbf2-4ee3-85b7-b61075714d00'
uuid = '8af2cdb4-cbf2-4ee3-85b7-b61075714d00::eb9f8e91-f383-4575-a549-e0b4bb52042e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmQaw8DjDC7Kg5jNXSqZmGHALfc8mkSPcnZDW4kbyAByNo'
id = 'tasks::dc365931-7393-4734-ab3c-2ec810aa3778'
uuid = 'dc365931-7393-4734-ab3c-2ec810aa3778::eb9f8e91-f383-4575-a549-e0b4bb52042e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmZmH2PiWxaS7epZWJoPtop7PEj9eNSGBpkcg2ydSA4W2Y'
id = 'fields::5a5a8d6a-a1a0-4e5f-ac50-e11aec41c616'
uuid = '5a5a8d6a-a1a0-4e5f-ac50-e11aec41c616::eb9f8e91-f383-4575-a549-e0b4bb52042e'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmSkJaa2ceaJhxeqksvLFtMrYxaU2Qmvvf3aZSi9J75EiG'
id = 'personalinformation::2ea0158a-ff99-4795-bbfb-ae157fd9a467'
uuid = '2ea0158a-ff99-4795-bbfb-ae157fd9a467::eb9f8e91-f383-4575-a549-e0b4bb52042e'

[[instances]]
agent = '6261170b-2064-4920-be43-98cc7ca1d68b'
dna = 'origins::9f713c88-ba83-49a5-9222-e47b29e00327'
id = '6261170b-2064-4920-be43-98cc7ca1d68b'

[instances.storage]
path = '/tmp/tmp.LFoyV7RAql/tryorama/dq1pcd/6261170b-2064-4920-be43-98cc7ca1d68b'
type = 'lmdb'

[[instances]]
agent = '4b7641fe-145d-4217-9768-1e0bff70fdf5'
dna = 'tags::b524ebf4-f59c-40e4-8849-5fc719ca6742'
id = '4b7641fe-145d-4217-9768-1e0bff70fdf5'

[instances.storage]
path = '/tmp/tmp.LFoyV7RAql/tryorama/dq1pcd/4b7641fe-145d-4217-9768-1e0bff70fdf5'
type = 'lmdb'

[[instances]]
agent = 'ef5ba968-0048-4135-b831-a86b615a89b2'
dna = 'projects::1b16f44c-8b73-405f-bbbc-19a93162f443'
id = 'ef5ba968-0048-4135-b831-a86b615a89b2'

[instances.storage]
path = '/tmp/tmp.LFoyV7RAql/tryorama/dq1pcd/ef5ba968-0048-4135-b831-a86b615a89b2'
type = 'lmdb'

[[instances]]
agent = '01526dbb-17f7-42d4-8a26-01270b50eb73'
dna = 'projects::9eb3f03d-7dea-4dfc-a54a-45faa01e92d2'
id = '01526dbb-17f7-42d4-8a26-01270b50eb73'

[instances.storage]
path = '/tmp/tmp.LFoyV7RAql/tryorama/dq1pcd/01526dbb-17f7-42d4-8a26-01270b50eb73'
type = 'lmdb'

[[instances]]
agent = '15f5c748-e611-47c7-9d1b-7651e5c16d17'
dna = 'projects::e61e0bbd-f9a6-4e03-960a-4ff555e28c20'
id = '15f5c748-e611-47c7-9d1b-7651e5c16d17'

[instances.storage]
path = '/tmp/tmp.LFoyV7RAql/tryorama/dq1pcd/15f5c748-e611-47c7-9d1b-7651e5c16d17'
type = 'lmdb'

[[instances]]
agent = '68342fe4-c2e3-4568-836e-421722757c84'
dna = 'kanban::1b3cdb13-3a60-4f9e-b473-44ab68d510b6'
id = '68342fe4-c2e3-4568-836e-421722757c84'

[instances.storage]
path = '/tmp/tmp.LFoyV7RAql/tryorama/dq1pcd/68342fe4-c2e3-4568-836e-421722757c84'
type = 'lmdb'

[[instances]]
agent = '6025b761-26e0-42c2-ad96-8bdc1ce00c33'
dna = 'notes::da68efe4-53ee-45e6-9f72-999c364a39cf'
id = '6025b761-26e0-42c2-ad96-8bdc1ce00c33'

[instances.storage]
path = '/tmp/tmp.LFoyV7RAql/tryorama/dq1pcd/6025b761-26e0-42c2-ad96-8bdc1ce00c33'
type = 'lmdb'

[[instances]]
agent = '1b94be13-632b-4924-aa20-8f67113d7b9a'
dna = 'tasks::c74b5f26-755a-4b96-977c-240e3074db73'
id = '1b94be13-632b-4924-aa20-8f67113d7b9a'

[instances.storage]
path = '/tmp/tmp.LFoyV7RAql/tryorama/dq1pcd/1b94be13-632b-4924-aa20-8f67113d7b9a'
type = 'lmdb'

[[instances]]
agent = '57c01ed8-30ae-4fca-b6f9-40192821fed2'
dna = 'origins::fb20018f-4dc8-49c9-9fcd-9ab1bbf27fb0'
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'

[instances.storage]
path = '/tmp/tmp.LFoyV7RAql/tryorama/dq1pcd/57c01ed8-30ae-4fca-b6f9-40192821fed2'
type = 'lmdb'

[[instances]]
agent = '164449a2-e7d4-47dc-acc8-2fe317b8d9fe'
dna = 'origins::73e6e83e-b352-479d-bc18-287d2bd13e81'
id = '164449a2-e7d4-47dc-acc8-2fe317b8d9fe'

[instances.storage]
path = '/tmp/tmp.LFoyV7RAql/tryorama/dq1pcd/164449a2-e7d4-47dc-acc8-2fe317b8d9fe'
type = 'lmdb'

[[instances]]
agent = '95569e2e-0de2-4073-8a7d-579f87534c04'
dna = 'kanban::885ec18a-b1f0-434b-98cf-0ae143bd0506'
id = '95569e2e-0de2-4073-8a7d-579f87534c04'

[instances.storage]
path = '/tmp/tmp.LFoyV7RAql/tryorama/dq1pcd/95569e2e-0de2-4073-8a7d-579f87534c04'
type = 'lmdb'

[[instances]]
agent = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'
dna = 'notes::8af2cdb4-cbf2-4ee3-85b7-b61075714d00'
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'

[instances.storage]
path = '/tmp/tmp.LFoyV7RAql/tryorama/dq1pcd/a23de7fe-bff7-4e6e-87f0-f4c44d038888'
type = 'lmdb'

[[instances]]
agent = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
dna = 'tasks::dc365931-7393-4734-ab3c-2ec810aa3778'
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'

[instances.storage]
path = '/tmp/tmp.LFoyV7RAql/tryorama/dq1pcd/e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields::5a5a8d6a-a1a0-4e5f-ac50-e11aec41c616'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.LFoyV7RAql/tryorama/dq1pcd/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation::2ea0158a-ff99-4795-bbfb-ae157fd9a467'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.LFoyV7RAql/tryorama/dq1pcd/personalinformation'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = '6261170b-2064-4920-be43-98cc7ca1d68b'

[[interfaces.instances]]
id = '4b7641fe-145d-4217-9768-1e0bff70fdf5'

[[interfaces.instances]]
id = 'ef5ba968-0048-4135-b831-a86b615a89b2'

[[interfaces.instances]]
id = '01526dbb-17f7-42d4-8a26-01270b50eb73'

[[interfaces.instances]]
id = '15f5c748-e611-47c7-9d1b-7651e5c16d17'

[[interfaces.instances]]
id = '68342fe4-c2e3-4568-836e-421722757c84'

[[interfaces.instances]]
id = '6025b761-26e0-42c2-ad96-8bdc1ce00c33'

[[interfaces.instances]]
id = '1b94be13-632b-4924-aa20-8f67113d7b9a'

[[interfaces.instances]]
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'

[[interfaces.instances]]
id = '164449a2-e7d4-47dc-acc8-2fe317b8d9fe'

[[interfaces.instances]]
id = '95569e2e-0de2-4073-8a7d-579f87534c04'

[[interfaces.instances]]
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'

[[interfaces.instances]]
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[interfaces.driver]
port = 33000
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
