bridges = []
persistence_dir = '/tmp/tmp.OGr2YY1n4S/tryorama/UnBqBD'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = '6261170b-2064-4920-be43-98cc7ca1d68b'
keystore_file = '[UNUSED]'
name = 'phil::6261170b-2064-4920-be43-98cc7ca1d68b::5cf45145-e286-4724-9a12-f1c1de4399d5'
public_address = 'HcScI69ZBFPUNxr746oTRGHBtDisaqani9umVcTpZVdy5ph3ssZfOI7pFahb94i'
test_agent = true

[[agents]]
id = '41553681-4c82-4c8c-87bb-ae2a3d2ba4cc'
keystore_file = '[UNUSED]'
name = 'phil::41553681-4c82-4c8c-87bb-ae2a3d2ba4cc::5cf45145-e286-4724-9a12-f1c1de4399d5'
public_address = 'HcSciExHUBMgdqo4zrSuUDNBS6y7hifutps9aTS9mI6d63f4UJvtAatiaff53wa'
test_agent = true

[[agents]]
id = '4b7641fe-145d-4217-9768-1e0bff70fdf5'
keystore_file = '[UNUSED]'
name = 'phil::4b7641fe-145d-4217-9768-1e0bff70fdf5::5cf45145-e286-4724-9a12-f1c1de4399d5'
public_address = 'HcSCJ7YV6yFJrdpbf5DDQxN6Vpzcrfe3cGBZ3jAjDNeoj8danJ7w9OBvRIz99gi'
test_agent = true

[[agents]]
id = 'ef5ba968-0048-4135-b831-a86b615a89b2'
keystore_file = '[UNUSED]'
name = 'phil::ef5ba968-0048-4135-b831-a86b615a89b2::5cf45145-e286-4724-9a12-f1c1de4399d5'
public_address = 'HcScjPTfCP6Js9mjevp3IvmS5pB7k4awkCymj8uPOg9y5bybgAbvyNUQwuncv6i'
test_agent = true

[[agents]]
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'
keystore_file = '[UNUSED]'
name = 'phil::57c01ed8-30ae-4fca-b6f9-40192821fed2::5cf45145-e286-4724-9a12-f1c1de4399d5'
public_address = 'HcScjuXP4Xfppabvxv3PDBtg5Y4T9r6t443Gp6fUVEpKbmd6v5YgKXq8Jubue8z'
test_agent = true

[[agents]]
id = '164449a2-e7d4-47dc-acc8-2fe317b8d9fe'
keystore_file = '[UNUSED]'
name = 'phil::164449a2-e7d4-47dc-acc8-2fe317b8d9fe::5cf45145-e286-4724-9a12-f1c1de4399d5'
public_address = 'HcScId8SdpOUjqsjviH9kXSEgAHvzbpi7wYoiQdNAwp5vm4hRaPHZiydqthbtpi'
test_agent = true

[[agents]]
id = '95569e2e-0de2-4073-8a7d-579f87534c04'
keystore_file = '[UNUSED]'
name = 'phil::95569e2e-0de2-4073-8a7d-579f87534c04::5cf45145-e286-4724-9a12-f1c1de4399d5'
public_address = 'HcSCiKBm856gQgivmhCYnRpnfr3agjvh5GwRDSnWfn3hm4do3xytRzzSIdb3afr'
test_agent = true

[[agents]]
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'
keystore_file = '[UNUSED]'
name = 'phil::a23de7fe-bff7-4e6e-87f0-f4c44d038888::5cf45145-e286-4724-9a12-f1c1de4399d5'
public_address = 'HcScI3V7fJBDivmojtRApcq5Jhp3q9uth76gngYK9FZJkbm8xSwgr55ONpenwyi'
test_agent = true

[[agents]]
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
keystore_file = '[UNUSED]'
name = 'phil::e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a::5cf45145-e286-4724-9a12-f1c1de4399d5'
public_address = 'HcSCJgXVyMSyh85morrtBZqbhvzx7caqsC8gj97uXzTFi6a3xuusDyyIv5yxq9a'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'phil::fields::5cf45145-e286-4724-9a12-f1c1de4399d5'
public_address = 'HcSci777xBiVy3E6ptVuhymcGSnd7fhtkHZFH5Mg5Zixa6yhyHYXb6WY96vyw8z'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'phil::personalinformation::5cf45145-e286-4724-9a12-f1c1de4399d5'
public_address = 'HcScjcWAEDe97ia4zt5b38OV9vbNYtm4xqY9JHVoD45zji5b6sn3aMauJk9d3qi'
test_agent = true

[[agents]]
id = '0d765fcf-118f-4122-8f03-f5f9ba74e7fa'
keystore_file = '[UNUSED]'
name = 'phil::0d765fcf-118f-4122-8f03-f5f9ba74e7fa::5cf45145-e286-4724-9a12-f1c1de4399d5'
public_address = 'HcSCI7ATi3VnK7fk8gbwZOujpK4d5v6g8zswvhTmficajniwBefXN6buaynygca'
test_agent = true

[[agents]]
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
keystore_file = '[UNUSED]'
name = 'phil::0098d2a1-5668-4a5a-8ef8-503d58dd38ce::5cf45145-e286-4724-9a12-f1c1de4399d5'
public_address = 'HcScJGrrmVOkxn3ce4zjyomw9W7j334xeQwpmj8cBgb3jz7ngHUp8HHdNcw3zfr'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmRxmQojEEt1k51qR2VMPB3XWeFzZWzTDaM9y3yxQRPZgF'
id = 'origins-test::12331f06-069f-4cdb-9b1e-ac03365ebb47'
uuid = '12331f06-069f-4cdb-9b1e-ac03365ebb47::5cf45145-e286-4724-9a12-f1c1de4399d5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmNsDq2ZxwYpYJpjckiBMx3x6hzkyDP6TumUazWx613Ypc'
id = 'freckles-test::d148cb24-9cf9-4326-84fe-30f344ac4c7a'
uuid = 'd148cb24-9cf9-4326-84fe-30f344ac4c7a::5cf45145-e286-4724-9a12-f1c1de4399d5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tags/dna/dist/dna.dna.json'
hash = 'QmNNx3dBamasVUZTj4ndNKDVG55SsDih6rh6ujkDsAuW66'
id = 'tags-test'
uuid = '5cf45145-e286-4724-9a12-f1c1de4399d5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/projects/dna/dist/dna.dna.json'
hash = 'QmUEquqJWE2S682VMxMz8CTaeezjrSEWv3G9istwPhXT4d'
id = 'projects-test'
uuid = '5cf45145-e286-4724-9a12-f1c1de4399d5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmTA5wvmyqRM9uEBMKgj2SpWmu7JSYfMLDFPX1bvWT1T16'
id = 'origins-test'
uuid = '5cf45145-e286-4724-9a12-f1c1de4399d5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmVSYwEdbdSg7uA8F3iTAMhruf9ZHhKtDNan2pQkAnWvje'
id = 'origins-test::7bb4dd16-0e47-42d5-a3bb-15788d60c08a'
uuid = '7bb4dd16-0e47-42d5-a3bb-15788d60c08a::5cf45145-e286-4724-9a12-f1c1de4399d5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmYHEpBx2qAkJjensNS44yw5GYRiNJaQvspsvCGerEk3wL'
id = 'kanban-test'
uuid = '5cf45145-e286-4724-9a12-f1c1de4399d5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmSUMyCVrVrjwUSgq8zMVRBA5hZNbf9kt5CTiJtuin61zW'
id = 'notes-test'
uuid = '5cf45145-e286-4724-9a12-f1c1de4399d5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmTbHxkY1PTjQ9iaZnNuYBxgTsRvG69odb6AJitDiHuVid'
id = 'tasks-test'
uuid = '5cf45145-e286-4724-9a12-f1c1de4399d5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmaSDXg5QySqZHeWv3HT2izMR38vhp8CNsjtwATvzwCN29'
id = 'fields-test'
uuid = '5cf45145-e286-4724-9a12-f1c1de4399d5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmaQUpu2WBR5DSz6CVzVWCAsMCoM7E1YNEXeS6UxbqaQzA'
id = 'personalinformation-test::2d30ba92-813b-43cc-a48f-b59c8ba685d8'
uuid = '2d30ba92-813b-43cc-a48f-b59c8ba685d8::5cf45145-e286-4724-9a12-f1c1de4399d5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'Qme8T2BHJi2odu6q5QFvavrKvSmqonM1YQ9874grqhqUmJ'
id = 'freckles-test::c7808603-181b-4903-a367-6ba4516d3eee'
uuid = 'c7808603-181b-4903-a367-6ba4516d3eee::5cf45145-e286-4724-9a12-f1c1de4399d5'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmawXMPvnjxgFjoWuT4pLFW1jzsZo6i42q6P5f9YdQvkKi'
id = 'freckles-test::01996035-6342-4d18-856b-29a242c955ad'
uuid = '01996035-6342-4d18-856b-29a242c955ad::5cf45145-e286-4724-9a12-f1c1de4399d5'

[[instances]]
agent = '6261170b-2064-4920-be43-98cc7ca1d68b'
dna = 'origins-test::12331f06-069f-4cdb-9b1e-ac03365ebb47'
id = '6261170b-2064-4920-be43-98cc7ca1d68b'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/UnBqBD/6261170b-2064-4920-be43-98cc7ca1d68b'
type = 'lmdb'

[[instances]]
agent = '41553681-4c82-4c8c-87bb-ae2a3d2ba4cc'
dna = 'freckles-test::d148cb24-9cf9-4326-84fe-30f344ac4c7a'
id = '41553681-4c82-4c8c-87bb-ae2a3d2ba4cc'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/UnBqBD/41553681-4c82-4c8c-87bb-ae2a3d2ba4cc'
type = 'lmdb'

[[instances]]
agent = '4b7641fe-145d-4217-9768-1e0bff70fdf5'
dna = 'tags-test'
id = '4b7641fe-145d-4217-9768-1e0bff70fdf5'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/UnBqBD/4b7641fe-145d-4217-9768-1e0bff70fdf5'
type = 'lmdb'

[[instances]]
agent = 'ef5ba968-0048-4135-b831-a86b615a89b2'
dna = 'projects-test'
id = 'ef5ba968-0048-4135-b831-a86b615a89b2'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/UnBqBD/ef5ba968-0048-4135-b831-a86b615a89b2'
type = 'lmdb'

[[instances]]
agent = '57c01ed8-30ae-4fca-b6f9-40192821fed2'
dna = 'origins-test'
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/UnBqBD/57c01ed8-30ae-4fca-b6f9-40192821fed2'
type = 'lmdb'

[[instances]]
agent = '164449a2-e7d4-47dc-acc8-2fe317b8d9fe'
dna = 'origins-test::7bb4dd16-0e47-42d5-a3bb-15788d60c08a'
id = '164449a2-e7d4-47dc-acc8-2fe317b8d9fe'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/UnBqBD/164449a2-e7d4-47dc-acc8-2fe317b8d9fe'
type = 'lmdb'

[[instances]]
agent = '95569e2e-0de2-4073-8a7d-579f87534c04'
dna = 'kanban-test'
id = '95569e2e-0de2-4073-8a7d-579f87534c04'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/UnBqBD/95569e2e-0de2-4073-8a7d-579f87534c04'
type = 'lmdb'

[[instances]]
agent = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'
dna = 'notes-test'
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/UnBqBD/a23de7fe-bff7-4e6e-87f0-f4c44d038888'
type = 'lmdb'

[[instances]]
agent = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
dna = 'tasks-test'
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/UnBqBD/e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/UnBqBD/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::2d30ba92-813b-43cc-a48f-b59c8ba685d8'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/UnBqBD/personalinformation'
type = 'lmdb'

[[instances]]
agent = '0d765fcf-118f-4122-8f03-f5f9ba74e7fa'
dna = 'freckles-test::c7808603-181b-4903-a367-6ba4516d3eee'
id = '0d765fcf-118f-4122-8f03-f5f9ba74e7fa'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/UnBqBD/0d765fcf-118f-4122-8f03-f5f9ba74e7fa'
type = 'lmdb'

[[instances]]
agent = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
dna = 'freckles-test::01996035-6342-4d18-856b-29a242c955ad'
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/UnBqBD/0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = '6261170b-2064-4920-be43-98cc7ca1d68b'

[[interfaces.instances]]
id = '41553681-4c82-4c8c-87bb-ae2a3d2ba4cc'

[[interfaces.instances]]
id = '4b7641fe-145d-4217-9768-1e0bff70fdf5'

[[interfaces.instances]]
id = 'ef5ba968-0048-4135-b831-a86b615a89b2'

[[interfaces.instances]]
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'

[[interfaces.instances]]
id = '164449a2-e7d4-47dc-acc8-2fe317b8d9fe'

[[interfaces.instances]]
id = '95569e2e-0de2-4073-8a7d-579f87534c04'

[[interfaces.instances]]
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'

[[interfaces.instances]]
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = '0d765fcf-118f-4122-8f03-f5f9ba74e7fa'

[[interfaces.instances]]
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'

[interfaces.driver]
port = 33000
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
