bridges = []
persistence_dir = '/tmp/tmp.OGr2YY1n4S/tryorama/M5E7dk'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = '4b7641fe-145d-4217-9768-1e0bff70fdf5'
keystore_file = '[UNUSED]'
name = 'lucy::4b7641fe-145d-4217-9768-1e0bff70fdf5::e127e16d-fbd9-48e5-a23e-0c7b1f75d270'
public_address = 'HcSCivQ7deRmhpfyyqIwpe5IXA4es3abnIr9m6NMpBJzpdx4h6SjrU3MKXhwzwi'
test_agent = true

[[agents]]
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'
keystore_file = '[UNUSED]'
name = 'lucy::57c01ed8-30ae-4fca-b6f9-40192821fed2::e127e16d-fbd9-48e5-a23e-0c7b1f75d270'
public_address = 'HcScIkYvmJ73kum7hfYCt3ibi778YUybyr9TDZDGvqk7nvgc5H8pW3KfzIBfgda'
test_agent = true

[[agents]]
id = '95569e2e-0de2-4073-8a7d-579f87534c04'
keystore_file = '[UNUSED]'
name = 'lucy::95569e2e-0de2-4073-8a7d-579f87534c04::e127e16d-fbd9-48e5-a23e-0c7b1f75d270'
public_address = 'HcScimAUI63Pxq6x875pXgK8JGxSu6r8kmImqhmCcytrq3zhK9jUXQUcrruzbfa'
test_agent = true

[[agents]]
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'
keystore_file = '[UNUSED]'
name = 'lucy::a23de7fe-bff7-4e6e-87f0-f4c44d038888::e127e16d-fbd9-48e5-a23e-0c7b1f75d270'
public_address = 'HcSCJtgWMa64gzbajaqGvN3ZMjGsn65tqz868tke58u56cq4WSpnnzNwmynjoxr'
test_agent = true

[[agents]]
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
keystore_file = '[UNUSED]'
name = 'lucy::e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a::e127e16d-fbd9-48e5-a23e-0c7b1f75d270'
public_address = 'HcSCiYFFqj9enjvm8fSOSQ86cQtZ6ydb463rQKefsBiex753z7ZM3iuJSpuncui'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'lucy::fields::e127e16d-fbd9-48e5-a23e-0c7b1f75d270'
public_address = 'HcScindA6PDnv88hntcyKKIg8Nqahiw4j9IDIZrx6Yse87uv9sejoj86376776i'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'lucy::personalinformation::e127e16d-fbd9-48e5-a23e-0c7b1f75d270'
public_address = 'HcSCjCbbH77Etc3j4f8aVow9bJ8Ygchyb6ytoaRE5vbna5u4Ab99TSJ378caghz'
test_agent = true

[[agents]]
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
keystore_file = '[UNUSED]'
name = 'lucy::0098d2a1-5668-4a5a-8ef8-503d58dd38ce::e127e16d-fbd9-48e5-a23e-0c7b1f75d270'
public_address = 'HcScip4pW6RkUbhuy8P5cqTYPwRsdf84qGAYk6A3whfs8r74okHC9oqnxdris7a'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tags/dna/dist/dna.dna.json'
hash = 'QmU8WXdQcYU5Mjd624YrDwUVow49qq4uE7u9dnsePE3cGa'
id = 'tags-test'
uuid = 'e127e16d-fbd9-48e5-a23e-0c7b1f75d270'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmNgqQPR4AfK6qAu1Ee36SgZB5hdFLvmmdmJ5DNVEdTS7r'
id = 'origins-test'
uuid = 'e127e16d-fbd9-48e5-a23e-0c7b1f75d270'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmX2zNDceP283yYnDZQEKCTVXdxXM2ydEWYTVna9BxvnVX'
id = 'kanban-test'
uuid = 'e127e16d-fbd9-48e5-a23e-0c7b1f75d270'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmYNPfDxsJ53Lv4jUr8fm1u3oah1QsgBndF5Z8rg96X1Uk'
id = 'notes-test'
uuid = 'e127e16d-fbd9-48e5-a23e-0c7b1f75d270'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmVp3peaRusBTz5Hib6j2xU9A4dDtkTfYzcm4PMpwn1LK4'
id = 'tasks-test'
uuid = 'e127e16d-fbd9-48e5-a23e-0c7b1f75d270'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmcusbVxHZwsTC2ccuHKZPUe4bGmsdHUvuWwE1YJhbxjeU'
id = 'fields-test'
uuid = 'e127e16d-fbd9-48e5-a23e-0c7b1f75d270'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmZCcoMpTTqMBdUSeWgcCuh1Rv2pRf7Fy4qXXP9FXnCsoo'
id = 'personalinformation-test::aba504c3-1e7e-4ba5-b453-9f5fcfbe64fa'
uuid = 'aba504c3-1e7e-4ba5-b453-9f5fcfbe64fa::e127e16d-fbd9-48e5-a23e-0c7b1f75d270'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmXfaJ8ZjjTFvSKCZNuBj7QgMAqNHTFFi3HASXbqhajDaE'
id = 'freckles-test::3f0aa4d8-81bd-4f44-93af-007552748dac'
uuid = '3f0aa4d8-81bd-4f44-93af-007552748dac::e127e16d-fbd9-48e5-a23e-0c7b1f75d270'

[[instances]]
agent = '4b7641fe-145d-4217-9768-1e0bff70fdf5'
dna = 'tags-test'
id = '4b7641fe-145d-4217-9768-1e0bff70fdf5'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/M5E7dk/4b7641fe-145d-4217-9768-1e0bff70fdf5'
type = 'lmdb'

[[instances]]
agent = '57c01ed8-30ae-4fca-b6f9-40192821fed2'
dna = 'origins-test'
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/M5E7dk/57c01ed8-30ae-4fca-b6f9-40192821fed2'
type = 'lmdb'

[[instances]]
agent = '95569e2e-0de2-4073-8a7d-579f87534c04'
dna = 'kanban-test'
id = '95569e2e-0de2-4073-8a7d-579f87534c04'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/M5E7dk/95569e2e-0de2-4073-8a7d-579f87534c04'
type = 'lmdb'

[[instances]]
agent = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'
dna = 'notes-test'
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/M5E7dk/a23de7fe-bff7-4e6e-87f0-f4c44d038888'
type = 'lmdb'

[[instances]]
agent = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
dna = 'tasks-test'
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/M5E7dk/e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/M5E7dk/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::aba504c3-1e7e-4ba5-b453-9f5fcfbe64fa'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/M5E7dk/personalinformation'
type = 'lmdb'

[[instances]]
agent = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
dna = 'freckles-test::3f0aa4d8-81bd-4f44-93af-007552748dac'
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/M5E7dk/0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = '4b7641fe-145d-4217-9768-1e0bff70fdf5'

[[interfaces.instances]]
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'

[[interfaces.instances]]
id = '95569e2e-0de2-4073-8a7d-579f87534c04'

[[interfaces.instances]]
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'

[[interfaces.instances]]
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'

[interfaces.driver]
port = 33001
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
