bridges = []
persistence_dir = '/tmp/tmp.BQyMjyicr6/tryorama/8fTbhx'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = '4b7641fe-145d-4217-9768-1e0bff70fdf5'
keystore_file = '[UNUSED]'
name = 'mary::4b7641fe-145d-4217-9768-1e0bff70fdf5::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'
public_address = 'HcScIFqUVY9J96qg4ri37qnIIPypmpjzgZap87B4V69KsDrjy74yFQ4saXRsusi'
test_agent = true

[[agents]]
id = '95569e2e-0de2-4073-8a7d-579f87534c04'
keystore_file = '[UNUSED]'
name = 'mary::95569e2e-0de2-4073-8a7d-579f87534c04::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'
public_address = 'HcSCISghm4M3ogwafvuEqrr38qdevnvra46M9hAHJQXahndo5EoXvZoBvta9gsz'
test_agent = true

[[agents]]
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'
keystore_file = '[UNUSED]'
name = 'mary::a23de7fe-bff7-4e6e-87f0-f4c44d038888::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'
public_address = 'HcSCjUJZeNxiop3atz3vAsafGCSxw9fm4b5QecueOMyka9cmS9PN6Wq4iZzeocr'
test_agent = true

[[agents]]
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
keystore_file = '[UNUSED]'
name = 'mary::e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'
public_address = 'HcScj3UbJg58p6Cqjh7su5e876ncfUgu9e7WaQE57wnPsm78g76X496AYfHKxuz'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'mary::fields::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'
public_address = 'HcSCJOR75Ahzmkw9596D93GRi3wKudugp456stzj653ytw44TmBu69KVym8awwi'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'mary::personalinformation::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'
public_address = 'HcSCihRhGhsn6ipoa35h4J8ntnsH6cz9nm7dwarKIAqo6u9snEHQdanmnqqscxi'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR-Holochain-redux/dna/tags/dna/dist/dna.dna.json'
hash = 'QmUC4E2yZQyQQ6UbvSkKG8D6E432SdGHuMULojtMBUDZpi'
id = 'tags::5bf9abe8-a4a9-411e-9dac-d6191a62a87c'
uuid = '5bf9abe8-a4a9-411e-9dac-d6191a62a87c::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR-Holochain-redux/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmejcBj2Zr2Rog9dAk4xBZKdSVgCZhig1TgiePWh9exam8'
id = 'kanban::d5199a30-2b6e-4756-b6ef-84fc1c5422b1'
uuid = 'd5199a30-2b6e-4756-b6ef-84fc1c5422b1::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR-Holochain-redux/dna/notes/dna/dist/dna.dna.json'
hash = 'QmdJ3DS3g3PZwXZtB4VRNhxwbgHCZQ1GGdxF65LBfjrWjs'
id = 'notes::c78a9590-c57b-4750-9ca2-b73c53a01110'
uuid = 'c78a9590-c57b-4750-9ca2-b73c53a01110::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR-Holochain-redux/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmWjVjtrfovwbJseu72kzLijqpo1yMU3xSjNHetULqVPWe'
id = 'tasks::c48b7988-bccd-431b-b72a-60331fbcedbb'
uuid = 'c48b7988-bccd-431b-b72a-60331fbcedbb::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR-Holochain-redux/dna/curated_fields/dna/dist/dna.dna.json'
hash = 'QmZBy9hXpDEcnr43wV6CrEGb4GhwhpUeBTJ3U2avPCmnX2'
id = 'fields::96960c3f-1036-4e6a-96f1-ef2eebb57f41'
uuid = '96960c3f-1036-4e6a-96f1-ef2eebb57f41::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR-Holochain-redux/dna/personal_information/dna/dist/dna.dna.json'
hash = 'QmdBpMPymYqMbfPH1iHNTwwAF4RP7a2ynT1ZyQfkYTT2cU'
id = 'personalinformation::75bf49b5-a211-41fd-adae-f876e7d6f9d3'
uuid = '75bf49b5-a211-41fd-adae-f876e7d6f9d3::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'

[[instances]]
agent = '4b7641fe-145d-4217-9768-1e0bff70fdf5'
dna = 'tags::5bf9abe8-a4a9-411e-9dac-d6191a62a87c'
id = '4b7641fe-145d-4217-9768-1e0bff70fdf5'

[instances.storage]
path = '/tmp/tmp.BQyMjyicr6/tryorama/8fTbhx/4b7641fe-145d-4217-9768-1e0bff70fdf5'
type = 'lmdb'

[[instances]]
agent = '95569e2e-0de2-4073-8a7d-579f87534c04'
dna = 'kanban::d5199a30-2b6e-4756-b6ef-84fc1c5422b1'
id = '95569e2e-0de2-4073-8a7d-579f87534c04'

[instances.storage]
path = '/tmp/tmp.BQyMjyicr6/tryorama/8fTbhx/95569e2e-0de2-4073-8a7d-579f87534c04'
type = 'lmdb'

[[instances]]
agent = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'
dna = 'notes::c78a9590-c57b-4750-9ca2-b73c53a01110'
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'

[instances.storage]
path = '/tmp/tmp.BQyMjyicr6/tryorama/8fTbhx/a23de7fe-bff7-4e6e-87f0-f4c44d038888'
type = 'lmdb'

[[instances]]
agent = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
dna = 'tasks::c48b7988-bccd-431b-b72a-60331fbcedbb'
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'

[instances.storage]
path = '/tmp/tmp.BQyMjyicr6/tryorama/8fTbhx/e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields::96960c3f-1036-4e6a-96f1-ef2eebb57f41'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.BQyMjyicr6/tryorama/8fTbhx/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation::75bf49b5-a211-41fd-adae-f876e7d6f9d3'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.BQyMjyicr6/tryorama/8fTbhx/personalinformation'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'developer-interface'

[[interfaces.instances]]
id = '4b7641fe-145d-4217-9768-1e0bff70fdf5'

[[interfaces.instances]]
id = '95569e2e-0de2-4073-8a7d-579f87534c04'

[[interfaces.instances]]
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'

[[interfaces.instances]]
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[interfaces.driver]
port = 43001
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
