bridges = []
persistence_dir = '/tmp/tmp.OGr2YY1n4S/tryorama/94wHGW'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = '4b7641fe-145d-4217-9768-1e0bff70fdf5'
keystore_file = '[UNUSED]'
name = 'lucy::4b7641fe-145d-4217-9768-1e0bff70fdf5::35ceca92-68ff-4c51-af9d-91a7339c3f05'
public_address = 'HcSCj3TdZK8g5xmchi5OM6uZtT5oyya8quEtYHZbH3739gefdIbTQi78qF4eqoz'
test_agent = true

[[agents]]
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'
keystore_file = '[UNUSED]'
name = 'lucy::57c01ed8-30ae-4fca-b6f9-40192821fed2::35ceca92-68ff-4c51-af9d-91a7339c3f05'
public_address = 'HcScjaZE3sCh8yuuhz8xUFpFKwm6rg4w8fW3QZQk35N4vwqcIOYSwDNQh6i5hqi'
test_agent = true

[[agents]]
id = '95569e2e-0de2-4073-8a7d-579f87534c04'
keystore_file = '[UNUSED]'
name = 'lucy::95569e2e-0de2-4073-8a7d-579f87534c04::35ceca92-68ff-4c51-af9d-91a7339c3f05'
public_address = 'HcSci654zCsMt3KobacphE3Nc7UDcdtw36OyQz9wY35vvuofrvO6PIPcu8u55sr'
test_agent = true

[[agents]]
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'
keystore_file = '[UNUSED]'
name = 'lucy::a23de7fe-bff7-4e6e-87f0-f4c44d038888::35ceca92-68ff-4c51-af9d-91a7339c3f05'
public_address = 'HcScjfVH4v5UYxdbu54O96Uzd843etyUxDIah6AN8kY8cdd36Onrwfab5Gqhvfz'
test_agent = true

[[agents]]
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
keystore_file = '[UNUSED]'
name = 'lucy::e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a::35ceca92-68ff-4c51-af9d-91a7339c3f05'
public_address = 'HcScj4Aiai4UBj68yqyfBwpPVs7jxnc8xBntbgMoQp587emse5654E7nDJ6ERQa'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'lucy::fields::35ceca92-68ff-4c51-af9d-91a7339c3f05'
public_address = 'HcSCIbPz5KXreq5tjh8cTQVgskkwvoxhddGQZ5ccpYjpdociUbpiZPS9Vr9rvui'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'lucy::personalinformation::35ceca92-68ff-4c51-af9d-91a7339c3f05'
public_address = 'HcSCj6Ty9Cvxcrssoi5qbZvDWfUwg7fuh7Yc9Y7Ctt5tpwz64tfTPxgVxtstm9a'
test_agent = true

[[agents]]
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
keystore_file = '[UNUSED]'
name = 'lucy::0098d2a1-5668-4a5a-8ef8-503d58dd38ce::35ceca92-68ff-4c51-af9d-91a7339c3f05'
public_address = 'HcSCiYt5Hawyx5oodc8RFz5ag78cSfkc68IqQc6KGJa7jceixpY9TKwWYsbzm3a'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tags/dna/dist/dna.dna.json'
hash = 'QmTuYM5A1D69Tn6kx56WbwDCLdathNNifhhPbXcuXm6oeo'
id = 'tags-test::c8fe6dff-6abb-4ae5-ba4e-16a364449ad8'
uuid = 'c8fe6dff-6abb-4ae5-ba4e-16a364449ad8::35ceca92-68ff-4c51-af9d-91a7339c3f05'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmVnRzjDJaqZQ1yJatKMMrDHyUYiwKeKJ2SmCkhxgxfZPH'
id = 'origins-test::92ef6313-c4b9-4666-aae6-200a400b7a95'
uuid = '92ef6313-c4b9-4666-aae6-200a400b7a95::35ceca92-68ff-4c51-af9d-91a7339c3f05'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmQfqGacDDG4bUf9ZAuYoFkNeVDuSSnAmqK98ZM9AnSgag'
id = 'kanban-test::c6b33d19-e46c-407d-956e-fa3cfaf3c548'
uuid = 'c6b33d19-e46c-407d-956e-fa3cfaf3c548::35ceca92-68ff-4c51-af9d-91a7339c3f05'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmSpqsDFj111NiimiXZtHJr8p9ZzasJ4LCLh8woNthYSPp'
id = 'notes-test::8dc07389-faf2-43e1-a05c-ed3be7212677'
uuid = '8dc07389-faf2-43e1-a05c-ed3be7212677::35ceca92-68ff-4c51-af9d-91a7339c3f05'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmQEgSbvfmigdskoN93dwo4dRHodFVFiiHyGgvPoHPfm13'
id = 'tasks-test::0b459fc1-9319-4ee0-99c5-63c2bc25efbb'
uuid = '0b459fc1-9319-4ee0-99c5-63c2bc25efbb::35ceca92-68ff-4c51-af9d-91a7339c3f05'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmaLV4bBfKhkVN6HcWCSWXFTjgK9iRqxRcViKp5geDhZTF'
id = 'fields-test::dfda931b-ae08-43dd-ac65-15af143562ac'
uuid = 'dfda931b-ae08-43dd-ac65-15af143562ac::35ceca92-68ff-4c51-af9d-91a7339c3f05'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmWjY1MB8Fbawdpu61KpGCjx7mswwgN6CxqaRisih6Svg8'
id = 'personalinformation-test::f3c57a61-7b18-4f50-a857-70afd061d938'
uuid = 'f3c57a61-7b18-4f50-a857-70afd061d938::35ceca92-68ff-4c51-af9d-91a7339c3f05'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmTD4ifid9tgKKdZ6wx6uBoqZzMDFkoNtEbpaF7Y23n38t'
id = 'freckles-test::ebf8e8c2-11db-40c0-b975-b3ebd56b95d3'
uuid = 'ebf8e8c2-11db-40c0-b975-b3ebd56b95d3::35ceca92-68ff-4c51-af9d-91a7339c3f05'

[[instances]]
agent = '4b7641fe-145d-4217-9768-1e0bff70fdf5'
dna = 'tags-test::c8fe6dff-6abb-4ae5-ba4e-16a364449ad8'
id = '4b7641fe-145d-4217-9768-1e0bff70fdf5'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/94wHGW/4b7641fe-145d-4217-9768-1e0bff70fdf5'
type = 'lmdb'

[[instances]]
agent = '57c01ed8-30ae-4fca-b6f9-40192821fed2'
dna = 'origins-test::92ef6313-c4b9-4666-aae6-200a400b7a95'
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/94wHGW/57c01ed8-30ae-4fca-b6f9-40192821fed2'
type = 'lmdb'

[[instances]]
agent = '95569e2e-0de2-4073-8a7d-579f87534c04'
dna = 'kanban-test::c6b33d19-e46c-407d-956e-fa3cfaf3c548'
id = '95569e2e-0de2-4073-8a7d-579f87534c04'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/94wHGW/95569e2e-0de2-4073-8a7d-579f87534c04'
type = 'lmdb'

[[instances]]
agent = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'
dna = 'notes-test::8dc07389-faf2-43e1-a05c-ed3be7212677'
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/94wHGW/a23de7fe-bff7-4e6e-87f0-f4c44d038888'
type = 'lmdb'

[[instances]]
agent = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
dna = 'tasks-test::0b459fc1-9319-4ee0-99c5-63c2bc25efbb'
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/94wHGW/e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test::dfda931b-ae08-43dd-ac65-15af143562ac'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/94wHGW/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::f3c57a61-7b18-4f50-a857-70afd061d938'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/94wHGW/personalinformation'
type = 'lmdb'

[[instances]]
agent = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
dna = 'freckles-test::ebf8e8c2-11db-40c0-b975-b3ebd56b95d3'
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/94wHGW/0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = '4b7641fe-145d-4217-9768-1e0bff70fdf5'

[[interfaces.instances]]
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'

[[interfaces.instances]]
id = '95569e2e-0de2-4073-8a7d-579f87534c04'

[[interfaces.instances]]
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'

[[interfaces.instances]]
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'

[interfaces.driver]
port = 33001
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
