bridges = []
persistence_dir = '/tmp/tmp.1KXds5iZNc/tryorama/YwI5dM'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = '4b7641fe-145d-4217-9768-1e0bff70fdf5'
keystore_file = '[UNUSED]'
name = 'mary::4b7641fe-145d-4217-9768-1e0bff70fdf5::9a5f1c37-51cc-4213-ba34-0e5bca522bc8'
public_address = 'HcScjZ85z7espeofne7m5g3v5R5VvNA6gE3PqhQ8TMx3yjtj3O3iwSrZa6Rxuhz'
test_agent = true

[[agents]]
id = '95569e2e-0de2-4073-8a7d-579f87534c04'
keystore_file = '[UNUSED]'
name = 'mary::95569e2e-0de2-4073-8a7d-579f87534c04::9a5f1c37-51cc-4213-ba34-0e5bca522bc8'
public_address = 'HcSCiWmmmuZj4zdcue8B55Hp4HUuvIes5c6D6iD9zqrdyfbrtt3MVCs4VXm9hti'
test_agent = true

[[agents]]
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'
keystore_file = '[UNUSED]'
name = 'mary::a23de7fe-bff7-4e6e-87f0-f4c44d038888::9a5f1c37-51cc-4213-ba34-0e5bca522bc8'
public_address = 'HcSCI4MJsuRJ5bruqe74g7NnjVGdxb4g8Rk6g36XotOppc8v38s8zH8bKpSPgea'
test_agent = true

[[agents]]
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
keystore_file = '[UNUSED]'
name = 'mary::e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a::9a5f1c37-51cc-4213-ba34-0e5bca522bc8'
public_address = 'HcScjCvpcJvourqsqoEv3Ut7e9VUusuyxZtNuTqtsxm3zam93xJ6WHD676HdZya'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'mary::fields::9a5f1c37-51cc-4213-ba34-0e5bca522bc8'
public_address = 'HcScj7qYoq5Bgg8v4rYC8vJuIskb3rpjdfwXZ477t6t4CjyxpJ8AE3SJ7DGzbfr'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'mary::personalinformation::9a5f1c37-51cc-4213-ba34-0e5bca522bc8'
public_address = 'HcSCi9gjMVqN54shig9Dc7hvFT3NQpb668Cw99OTM4pcHd5gW4g9t3qfKfQqydz'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tags/dna/dist/dna.dna.json'
hash = 'QmfDJXd8uvKApnapdY3KBbtcsfPNSs7rRgLYkE4FKtrMbb'
id = 'tags::33c7a575-6aab-46d5-94d8-79081c5c5b39'
uuid = '33c7a575-6aab-46d5-94d8-79081c5c5b39::9a5f1c37-51cc-4213-ba34-0e5bca522bc8'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmechRHjCEkfvuDDDVhxMAyEUaqngzBpndnPM2LC4At4D1'
id = 'kanban::9e448913-e88c-4d77-bec5-9f58197b16e1'
uuid = '9e448913-e88c-4d77-bec5-9f58197b16e1::9a5f1c37-51cc-4213-ba34-0e5bca522bc8'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmVdkArkF7wTGiQ9j6tbrtrefUZezqtyqsRaXSarvG2CmG'
id = 'notes::f38f175e-0ed9-4a27-be5f-ece5a7a568a4'
uuid = 'f38f175e-0ed9-4a27-be5f-ece5a7a568a4::9a5f1c37-51cc-4213-ba34-0e5bca522bc8'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmU5BDQTV2K1zWv8FfBU1ajx9vMnjLNqmZJu3H2pXuXJo2'
id = 'tasks::fe7ab10c-ba2c-44eb-a04a-34f3925e0e53'
uuid = 'fe7ab10c-ba2c-44eb-a04a-34f3925e0e53::9a5f1c37-51cc-4213-ba34-0e5bca522bc8'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curated_fields/dna/dist/dna.dna.json'
hash = 'QmT93QEMFFyyYHDMan6KnSukqL8MD5pP3r53SkDxAxgqBA'
id = 'fields::8d334630-e9f1-4a02-9282-2ab8bb6ca940'
uuid = '8d334630-e9f1-4a02-9282-2ab8bb6ca940::9a5f1c37-51cc-4213-ba34-0e5bca522bc8'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personal_information/dna/dist/dna.dna.json'
hash = 'QmV6mNLvH541WJfP9NPm3FB6i6qbeRX8NXuL2Wm6dmqAS3'
id = 'personalinformation::17895163-ca96-4467-be38-30d5f38784be'
uuid = '17895163-ca96-4467-be38-30d5f38784be::9a5f1c37-51cc-4213-ba34-0e5bca522bc8'

[[instances]]
agent = '4b7641fe-145d-4217-9768-1e0bff70fdf5'
dna = 'tags::33c7a575-6aab-46d5-94d8-79081c5c5b39'
id = '4b7641fe-145d-4217-9768-1e0bff70fdf5'

[instances.storage]
path = '/tmp/tmp.1KXds5iZNc/tryorama/YwI5dM/4b7641fe-145d-4217-9768-1e0bff70fdf5'
type = 'lmdb'

[[instances]]
agent = '95569e2e-0de2-4073-8a7d-579f87534c04'
dna = 'kanban::9e448913-e88c-4d77-bec5-9f58197b16e1'
id = '95569e2e-0de2-4073-8a7d-579f87534c04'

[instances.storage]
path = '/tmp/tmp.1KXds5iZNc/tryorama/YwI5dM/95569e2e-0de2-4073-8a7d-579f87534c04'
type = 'lmdb'

[[instances]]
agent = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'
dna = 'notes::f38f175e-0ed9-4a27-be5f-ece5a7a568a4'
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'

[instances.storage]
path = '/tmp/tmp.1KXds5iZNc/tryorama/YwI5dM/a23de7fe-bff7-4e6e-87f0-f4c44d038888'
type = 'lmdb'

[[instances]]
agent = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
dna = 'tasks::fe7ab10c-ba2c-44eb-a04a-34f3925e0e53'
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'

[instances.storage]
path = '/tmp/tmp.1KXds5iZNc/tryorama/YwI5dM/e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields::8d334630-e9f1-4a02-9282-2ab8bb6ca940'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.1KXds5iZNc/tryorama/YwI5dM/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation::17895163-ca96-4467-be38-30d5f38784be'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.1KXds5iZNc/tryorama/YwI5dM/personalinformation'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = '4b7641fe-145d-4217-9768-1e0bff70fdf5'

[[interfaces.instances]]
id = '95569e2e-0de2-4073-8a7d-579f87534c04'

[[interfaces.instances]]
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'

[[interfaces.instances]]
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[interfaces.driver]
port = 33001
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
