bridges = []
persistence_dir = '/tmp/tmp.BQyMjyicr6/tryorama/cCELcN'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = '4b7641fe-145d-4217-9768-1e0bff70fdf5'
keystore_file = '[UNUSED]'
name = 'rudy::4b7641fe-145d-4217-9768-1e0bff70fdf5::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'
public_address = 'HcScIRaeWRakac4wvwD3fG4Wwp86776Cci63V6SoXhpA55eokb9zic6eB6gobir'
test_agent = true

[[agents]]
id = '95569e2e-0de2-4073-8a7d-579f87534c04'
keystore_file = '[UNUSED]'
name = 'rudy::95569e2e-0de2-4073-8a7d-579f87534c04::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'
public_address = 'HcSCJS68CnMGr996i4hjnNmy5yVspg4d7gg7vGbevJypo7o7BjNFYvxIt833wwr'
test_agent = true

[[agents]]
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'
keystore_file = '[UNUSED]'
name = 'rudy::a23de7fe-bff7-4e6e-87f0-f4c44d038888::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'
public_address = 'HcSCJvXWbyHmuq4tcknb786a465cxk8m9gPN7kkpwIudsadbIqKof9rAyiokfxr'
test_agent = true

[[agents]]
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
keystore_file = '[UNUSED]'
name = 'rudy::e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'
public_address = 'HcSCJDj5V7wbdbh4aiD7N9MzCE3z3m5vyyFFGup5aYyf4v9bhug3PV8Jyq5dm5a'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'rudy::fields::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'
public_address = 'HcSCJ4y89nmSU6Qvcjd7EW8ZY4f3IndtuouX44HTN3j4MgtgPG3a8M6A3YWagvi'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'rudy::personalinformation::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'
public_address = 'HcScIQ5xxaXwj7tb9i6559RYy9Ic9mSb88FBP3v48TqVakyfTF7BhYroXie55az'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR-Holochain-redux/dna/tags/dna/dist/dna.dna.json'
hash = 'QmUC4E2yZQyQQ6UbvSkKG8D6E432SdGHuMULojtMBUDZpi'
id = 'tags::5bf9abe8-a4a9-411e-9dac-d6191a62a87c'
uuid = '5bf9abe8-a4a9-411e-9dac-d6191a62a87c::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR-Holochain-redux/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmejcBj2Zr2Rog9dAk4xBZKdSVgCZhig1TgiePWh9exam8'
id = 'kanban::d5199a30-2b6e-4756-b6ef-84fc1c5422b1'
uuid = 'd5199a30-2b6e-4756-b6ef-84fc1c5422b1::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR-Holochain-redux/dna/notes/dna/dist/dna.dna.json'
hash = 'QmdJ3DS3g3PZwXZtB4VRNhxwbgHCZQ1GGdxF65LBfjrWjs'
id = 'notes::c78a9590-c57b-4750-9ca2-b73c53a01110'
uuid = 'c78a9590-c57b-4750-9ca2-b73c53a01110::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR-Holochain-redux/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmWjVjtrfovwbJseu72kzLijqpo1yMU3xSjNHetULqVPWe'
id = 'tasks::c48b7988-bccd-431b-b72a-60331fbcedbb'
uuid = 'c48b7988-bccd-431b-b72a-60331fbcedbb::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR-Holochain-redux/dna/curated_fields/dna/dist/dna.dna.json'
hash = 'QmZBy9hXpDEcnr43wV6CrEGb4GhwhpUeBTJ3U2avPCmnX2'
id = 'fields::96960c3f-1036-4e6a-96f1-ef2eebb57f41'
uuid = '96960c3f-1036-4e6a-96f1-ef2eebb57f41::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR-Holochain-redux/dna/personal_information/dna/dist/dna.dna.json'
hash = 'QmRj2786CDs73t6daxg5MKwc3ViEHcwJbm1SsCRVf31wo2'
id = 'personalinformation::9fb4d7be-0eee-45e3-9f4e-544cde313ad3'
uuid = '9fb4d7be-0eee-45e3-9f4e-544cde313ad3::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'

[[instances]]
agent = '4b7641fe-145d-4217-9768-1e0bff70fdf5'
dna = 'tags::5bf9abe8-a4a9-411e-9dac-d6191a62a87c'
id = '4b7641fe-145d-4217-9768-1e0bff70fdf5'

[instances.storage]
path = '/tmp/tmp.BQyMjyicr6/tryorama/cCELcN/4b7641fe-145d-4217-9768-1e0bff70fdf5'
type = 'lmdb'

[[instances]]
agent = '95569e2e-0de2-4073-8a7d-579f87534c04'
dna = 'kanban::d5199a30-2b6e-4756-b6ef-84fc1c5422b1'
id = '95569e2e-0de2-4073-8a7d-579f87534c04'

[instances.storage]
path = '/tmp/tmp.BQyMjyicr6/tryorama/cCELcN/95569e2e-0de2-4073-8a7d-579f87534c04'
type = 'lmdb'

[[instances]]
agent = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'
dna = 'notes::c78a9590-c57b-4750-9ca2-b73c53a01110'
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'

[instances.storage]
path = '/tmp/tmp.BQyMjyicr6/tryorama/cCELcN/a23de7fe-bff7-4e6e-87f0-f4c44d038888'
type = 'lmdb'

[[instances]]
agent = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
dna = 'tasks::c48b7988-bccd-431b-b72a-60331fbcedbb'
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'

[instances.storage]
path = '/tmp/tmp.BQyMjyicr6/tryorama/cCELcN/e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields::96960c3f-1036-4e6a-96f1-ef2eebb57f41'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.BQyMjyicr6/tryorama/cCELcN/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation::9fb4d7be-0eee-45e3-9f4e-544cde313ad3'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.BQyMjyicr6/tryorama/cCELcN/personalinformation'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'developer-interface'

[[interfaces.instances]]
id = '4b7641fe-145d-4217-9768-1e0bff70fdf5'

[[interfaces.instances]]
id = '95569e2e-0de2-4073-8a7d-579f87534c04'

[[interfaces.instances]]
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'

[[interfaces.instances]]
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[interfaces.driver]
port = 43002
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
