bridges = []
persistence_dir = '/tmp/tmp.oytTivtHqk/tryorama/JezRVn'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'tags'
keystore_file = '[UNUSED]'
name = 'rudy::tags::85714226-e4da-4168-8bbe-208711747f45'
public_address = 'HcSci8mr4F4nat8ig6E7kGBX4Miieh8dewFyBhm8563Azyc5mYP3kb9ieF6qqqr'
test_agent = true

[[agents]]
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'
keystore_file = '[UNUSED]'
name = 'rudy::57c01ed8-30ae-4fca-b6f9-40192821fed2::85714226-e4da-4168-8bbe-208711747f45'
public_address = 'HcSCJoG3HROPqe59wazuEun9rBE5n4tr96zm6454pj7b3y85sJ6nV6D7MnI6qiz'
test_agent = true

[[agents]]
id = '164449a2-e7d4-47dc-acc8-2fe317b8d9fe'
keystore_file = '[UNUSED]'
name = 'rudy::164449a2-e7d4-47dc-acc8-2fe317b8d9fe::85714226-e4da-4168-8bbe-208711747f45'
public_address = 'HcSCiCExxhVjnyuivunwPTPfN334IfduzgsOYygapazmkyr9cWj4E8jGK8Vd5ez'
test_agent = true

[[agents]]
id = '95569e2e-0de2-4073-8a7d-579f87534c04'
keystore_file = '[UNUSED]'
name = 'rudy::95569e2e-0de2-4073-8a7d-579f87534c04::85714226-e4da-4168-8bbe-208711747f45'
public_address = 'HcSciJFECbOeky4cdb68H94p8B3IfW8bCBWUvrJRFeysdv3zCV6yZAQKsxckqyz'
test_agent = true

[[agents]]
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'
keystore_file = '[UNUSED]'
name = 'rudy::a23de7fe-bff7-4e6e-87f0-f4c44d038888::85714226-e4da-4168-8bbe-208711747f45'
public_address = 'HcScJGU3Dg4zSnqpuzq4Hx8zE8Gy8n6piaU7P7NfFeEx3ewumui6V5Z6fr6fuyi'
test_agent = true

[[agents]]
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
keystore_file = '[UNUSED]'
name = 'rudy::e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a::85714226-e4da-4168-8bbe-208711747f45'
public_address = 'HcSCjpQd5NV75uphvtw96Nf3hjSoK7jq8w4r7QNDgk3ie3reSno597kXZN6Epwa'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'rudy::fields::85714226-e4da-4168-8bbe-208711747f45'
public_address = 'HcSCJR4fOIrVpv86ydhdd56ZDpYYzfhrgn38sN3aAquO8v4kYMydBRy7tuiiusa'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'rudy::personalinformation::85714226-e4da-4168-8bbe-208711747f45'
public_address = 'HcSci78rjfDs7G3jugtsbYvbRD64eateuFmKijG5g8wkd8o6HDSOixpgqdoodjr'
test_agent = true

[[agents]]
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
keystore_file = '[UNUSED]'
name = 'rudy::0098d2a1-5668-4a5a-8ef8-503d58dd38ce::85714226-e4da-4168-8bbe-208711747f45'
public_address = 'HcScjOMg63dhnunbmaCfI9ItET9ah7is7U65tvpQEQdjygirpwb4n7gHYasx5ui'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tags/dna/dist/dna.dna.json'
hash = 'QmahPjjwrwGnyAiHxwD7rJYrWgPDbSLSfp9q9QeMsfW1au'
id = 'tags-test'
uuid = '85714226-e4da-4168-8bbe-208711747f45'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'Qma1Kx3K5zkNYS9M8u8tUdvSQDGshSLGRALCWhBqaLH8pD'
id = 'origins-test'
uuid = '85714226-e4da-4168-8bbe-208711747f45'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmeN7PysDefwiCgux4Lxff9jquve54Q6USbhYBeZ4LXAgC'
id = 'origins-test::72918820-5e32-4ca8-ae7e-fa6870ec5107'
uuid = '72918820-5e32-4ca8-ae7e-fa6870ec5107::85714226-e4da-4168-8bbe-208711747f45'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmceY1hA6v6WVsy3Zk4aRSdGiYA4QVkXiJtEndFrDCa99F'
id = 'kanban-test'
uuid = '85714226-e4da-4168-8bbe-208711747f45'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmSq98jJ9LU3nrk8RhYru87uC2SoT942qTqTjhoWhHb4Zt'
id = 'notes-test'
uuid = '85714226-e4da-4168-8bbe-208711747f45'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmPrgkyjgkbzmsLRUFWWdrw7sRzMnvmJRMuWqVMqLwaN6r'
id = 'tasks-test'
uuid = '85714226-e4da-4168-8bbe-208711747f45'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmR9EngDtCgr2VSwXFfJ8WrEMzmK2AFUrqRSFfLza5Wndf'
id = 'fields-test'
uuid = '85714226-e4da-4168-8bbe-208711747f45'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmVG7rohHwHUyhjqvAp3xdsf1fWEcFRTCjS7UqNFT5Zufm'
id = 'personalinformation-test::dea7c9b6-d889-4925-b701-b30576438378'
uuid = 'dea7c9b6-d889-4925-b701-b30576438378::85714226-e4da-4168-8bbe-208711747f45'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmYg43ANPS4oW1uYbiHQeBHmA2pwYTHXkfGCahjsBegR3u'
id = 'freckles-test::5681a9fa-3a5f-4f53-a219-bca278f0efc3'
uuid = '5681a9fa-3a5f-4f53-a219-bca278f0efc3::85714226-e4da-4168-8bbe-208711747f45'

[[instances]]
agent = 'tags'
dna = 'tags-test'
id = 'tags'

[instances.storage]
path = '/tmp/tmp.oytTivtHqk/tryorama/JezRVn/tags'
type = 'lmdb'

[[instances]]
agent = '57c01ed8-30ae-4fca-b6f9-40192821fed2'
dna = 'origins-test'
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'

[instances.storage]
path = '/tmp/tmp.oytTivtHqk/tryorama/JezRVn/57c01ed8-30ae-4fca-b6f9-40192821fed2'
type = 'lmdb'

[[instances]]
agent = '164449a2-e7d4-47dc-acc8-2fe317b8d9fe'
dna = 'origins-test::72918820-5e32-4ca8-ae7e-fa6870ec5107'
id = '164449a2-e7d4-47dc-acc8-2fe317b8d9fe'

[instances.storage]
path = '/tmp/tmp.oytTivtHqk/tryorama/JezRVn/164449a2-e7d4-47dc-acc8-2fe317b8d9fe'
type = 'lmdb'

[[instances]]
agent = '95569e2e-0de2-4073-8a7d-579f87534c04'
dna = 'kanban-test'
id = '95569e2e-0de2-4073-8a7d-579f87534c04'

[instances.storage]
path = '/tmp/tmp.oytTivtHqk/tryorama/JezRVn/95569e2e-0de2-4073-8a7d-579f87534c04'
type = 'lmdb'

[[instances]]
agent = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'
dna = 'notes-test'
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'

[instances.storage]
path = '/tmp/tmp.oytTivtHqk/tryorama/JezRVn/a23de7fe-bff7-4e6e-87f0-f4c44d038888'
type = 'lmdb'

[[instances]]
agent = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
dna = 'tasks-test'
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'

[instances.storage]
path = '/tmp/tmp.oytTivtHqk/tryorama/JezRVn/e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.oytTivtHqk/tryorama/JezRVn/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::dea7c9b6-d889-4925-b701-b30576438378'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.oytTivtHqk/tryorama/JezRVn/personalinformation'
type = 'lmdb'

[[instances]]
agent = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
dna = 'freckles-test::5681a9fa-3a5f-4f53-a219-bca278f0efc3'
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'

[instances.storage]
path = '/tmp/tmp.oytTivtHqk/tryorama/JezRVn/0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'tags'

[[interfaces.instances]]
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'

[[interfaces.instances]]
id = '164449a2-e7d4-47dc-acc8-2fe317b8d9fe'

[[interfaces.instances]]
id = '95569e2e-0de2-4073-8a7d-579f87534c04'

[[interfaces.instances]]
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'

[[interfaces.instances]]
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'

[interfaces.driver]
port = 33002
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
