bridges = []
persistence_dir = '/tmp/tmp.BM8H3lE45C/tryorama/It8wvB'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = '4b7641fe-145d-4217-9768-1e0bff70fdf5'
keystore_file = '[UNUSED]'
name = 'rudy::4b7641fe-145d-4217-9768-1e0bff70fdf5::39c7522a-0cf4-4eae-abe9-49ba89a8b4ed'
public_address = 'HcScJso3zSJE774vt6en8vjMdj95ssaphfkgezXT4M66i7n9CYtA5EkJk8dmtyr'
test_agent = true

[[agents]]
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'
keystore_file = '[UNUSED]'
name = 'rudy::57c01ed8-30ae-4fca-b6f9-40192821fed2::39c7522a-0cf4-4eae-abe9-49ba89a8b4ed'
public_address = 'HcSCIt3I5TatW8zzkp7RkOzdF55fNcb6hSKO5Rfmj9Kiqcg7vi98Qj6A4UH9Ker'
test_agent = true

[[agents]]
id = '164449a2-e7d4-47dc-acc8-2fe317b8d9fe'
keystore_file = '[UNUSED]'
name = 'rudy::164449a2-e7d4-47dc-acc8-2fe317b8d9fe::39c7522a-0cf4-4eae-abe9-49ba89a8b4ed'
public_address = 'HcScJo9k4dXQI3dv4yQTNQbEaWnycvczkQ4NZF9Qn6oWvew7mrAZmBxbeedwnhr'
test_agent = true

[[agents]]
id = '95569e2e-0de2-4073-8a7d-579f87534c04'
keystore_file = '[UNUSED]'
name = 'rudy::95569e2e-0de2-4073-8a7d-579f87534c04::39c7522a-0cf4-4eae-abe9-49ba89a8b4ed'
public_address = 'HcSciGJpuVHxbe7hvwFq5iaYF3eG7gi9fRa686NwZqy7n6hsvJoKdYRPbgjry9r'
test_agent = true

[[agents]]
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'
keystore_file = '[UNUSED]'
name = 'rudy::a23de7fe-bff7-4e6e-87f0-f4c44d038888::39c7522a-0cf4-4eae-abe9-49ba89a8b4ed'
public_address = 'HcScIpyXvKegbjfogiykq7jd4yVPuqd3x4ntdIWs6kiidmiaavTu7nU8nIkk3ua'
test_agent = true

[[agents]]
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
keystore_file = '[UNUSED]'
name = 'rudy::e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a::39c7522a-0cf4-4eae-abe9-49ba89a8b4ed'
public_address = 'HcScJ3tvfCtzrxybs98U456M5DoqEqcuam3qFmIVntvi74i4cG6jBj459WQCmkr'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'rudy::fields::39c7522a-0cf4-4eae-abe9-49ba89a8b4ed'
public_address = 'HcScj3yt7KqNefjptecG6IYoGC9S8epzw9nS5DRB3Ob6supmtwfj3eQNP9duy3i'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'rudy::personalinformation::39c7522a-0cf4-4eae-abe9-49ba89a8b4ed'
public_address = 'HcSCJBItc7ks5iqfq5o9uNCtGQPrxfbn3p4yPMTi6fImcq88mHXTmtiye3jybji'
test_agent = true

[[agents]]
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
keystore_file = '[UNUSED]'
name = 'rudy::0098d2a1-5668-4a5a-8ef8-503d58dd38ce::39c7522a-0cf4-4eae-abe9-49ba89a8b4ed'
public_address = 'HcScJR4jHqCyc5cp4d6SJ5OM7DRcYzzdxfDDFktIuj8phgypieqkDuK7g3ozfjz'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tags/dna/dist/dna.dna.json'
hash = 'QmbqayAkpV2WwJLr7uYMqVYhiZpqeAkLyHGEsu8TMCuaKy'
id = 'tags-test'
uuid = '39c7522a-0cf4-4eae-abe9-49ba89a8b4ed'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmRPeM5AFoNCTrTsVnLxPx19zJZnsRDgKjPJmDEpiwA2my'
id = 'origins-test'
uuid = '39c7522a-0cf4-4eae-abe9-49ba89a8b4ed'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmUtmwV5fKS6qSJvrThPYY6sJRbAGw5Mk2rhyvkFdUYJGd'
id = 'origins-test::062649f1-5984-4c63-8f66-83621ce9beea'
uuid = '062649f1-5984-4c63-8f66-83621ce9beea::39c7522a-0cf4-4eae-abe9-49ba89a8b4ed'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmXuZEKjM3ccnnuEZ1Ez2aoDynP2JdZhgVsnrwtugDWJRE'
id = 'kanban-test'
uuid = '39c7522a-0cf4-4eae-abe9-49ba89a8b4ed'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmRQP5SHLhRa86SsnahF3YRN6ExHHU3iLrbAaexEHWMY6t'
id = 'notes-test'
uuid = '39c7522a-0cf4-4eae-abe9-49ba89a8b4ed'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmX2beDouD8so6cXB1v7U5SeAd1ybuJt8kYvjfnVFNiUzJ'
id = 'tasks-test'
uuid = '39c7522a-0cf4-4eae-abe9-49ba89a8b4ed'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmVUbpyRmyu87adPJzLNynEWt8zy4QhNzYn6fcBXdAVrXw'
id = 'fields-test'
uuid = '39c7522a-0cf4-4eae-abe9-49ba89a8b4ed'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmfRzdfe1MVjQXdLVvPNLecQQv55Q4q256JMfoHk34UvWw'
id = 'personalinformation-test::52f97df9-8afb-4656-aa55-08e61faaff49'
uuid = '52f97df9-8afb-4656-aa55-08e61faaff49::39c7522a-0cf4-4eae-abe9-49ba89a8b4ed'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmVXLaQkPT4nZ2F4AZQKKqjFCUchwX1ynPZWAFK47K4rUA'
id = 'freckles-test::b4af4ec0-00a2-410a-b84a-96ef35bd9229'
uuid = 'b4af4ec0-00a2-410a-b84a-96ef35bd9229::39c7522a-0cf4-4eae-abe9-49ba89a8b4ed'

[[instances]]
agent = '4b7641fe-145d-4217-9768-1e0bff70fdf5'
dna = 'tags-test'
id = '4b7641fe-145d-4217-9768-1e0bff70fdf5'

[instances.storage]
path = '/tmp/tmp.BM8H3lE45C/tryorama/It8wvB/4b7641fe-145d-4217-9768-1e0bff70fdf5'
type = 'lmdb'

[[instances]]
agent = '57c01ed8-30ae-4fca-b6f9-40192821fed2'
dna = 'origins-test'
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'

[instances.storage]
path = '/tmp/tmp.BM8H3lE45C/tryorama/It8wvB/57c01ed8-30ae-4fca-b6f9-40192821fed2'
type = 'lmdb'

[[instances]]
agent = '164449a2-e7d4-47dc-acc8-2fe317b8d9fe'
dna = 'origins-test::062649f1-5984-4c63-8f66-83621ce9beea'
id = '164449a2-e7d4-47dc-acc8-2fe317b8d9fe'

[instances.storage]
path = '/tmp/tmp.BM8H3lE45C/tryorama/It8wvB/164449a2-e7d4-47dc-acc8-2fe317b8d9fe'
type = 'lmdb'

[[instances]]
agent = '95569e2e-0de2-4073-8a7d-579f87534c04'
dna = 'kanban-test'
id = '95569e2e-0de2-4073-8a7d-579f87534c04'

[instances.storage]
path = '/tmp/tmp.BM8H3lE45C/tryorama/It8wvB/95569e2e-0de2-4073-8a7d-579f87534c04'
type = 'lmdb'

[[instances]]
agent = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'
dna = 'notes-test'
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'

[instances.storage]
path = '/tmp/tmp.BM8H3lE45C/tryorama/It8wvB/a23de7fe-bff7-4e6e-87f0-f4c44d038888'
type = 'lmdb'

[[instances]]
agent = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
dna = 'tasks-test'
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'

[instances.storage]
path = '/tmp/tmp.BM8H3lE45C/tryorama/It8wvB/e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.BM8H3lE45C/tryorama/It8wvB/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::52f97df9-8afb-4656-aa55-08e61faaff49'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.BM8H3lE45C/tryorama/It8wvB/personalinformation'
type = 'lmdb'

[[instances]]
agent = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
dna = 'freckles-test::b4af4ec0-00a2-410a-b84a-96ef35bd9229'
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'

[instances.storage]
path = '/tmp/tmp.BM8H3lE45C/tryorama/It8wvB/0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = '4b7641fe-145d-4217-9768-1e0bff70fdf5'

[[interfaces.instances]]
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'

[[interfaces.instances]]
id = '164449a2-e7d4-47dc-acc8-2fe317b8d9fe'

[[interfaces.instances]]
id = '95569e2e-0de2-4073-8a7d-579f87534c04'

[[interfaces.instances]]
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'

[[interfaces.instances]]
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'

[interfaces.driver]
port = 33002
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
