bridges = []
persistence_dir = '/tmp/tmp.OGr2YY1n4S/tryorama/tZRG5c'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'ef5ba968-0048-4135-b831-a86b615a89b2'
keystore_file = '[UNUSED]'
name = 'arthur::ef5ba968-0048-4135-b831-a86b615a89b2::e127e16d-fbd9-48e5-a23e-0c7b1f75d270'
public_address = 'HcScIJt7I9XIRbpbhnZBqC7ekN499NiggoTZPyDVmgjnrqyrCWMCKb46DSr3vyr'
test_agent = true

[[agents]]
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'
keystore_file = '[UNUSED]'
name = 'arthur::57c01ed8-30ae-4fca-b6f9-40192821fed2::e127e16d-fbd9-48e5-a23e-0c7b1f75d270'
public_address = 'HcScIcAYy5sj375j87cA8yGW5PeOy899ujcxHh7A7K4r55vcz3qavO5eJKnvedi'
test_agent = true

[[agents]]
id = '95569e2e-0de2-4073-8a7d-579f87534c04'
keystore_file = '[UNUSED]'
name = 'arthur::95569e2e-0de2-4073-8a7d-579f87534c04::e127e16d-fbd9-48e5-a23e-0c7b1f75d270'
public_address = 'HcSCIsUFEuz3yegjmhAgT8yssmfs4otzo8JmYJiy34ukzzqwKahdgT3ZEnwroar'
test_agent = true

[[agents]]
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'
keystore_file = '[UNUSED]'
name = 'arthur::a23de7fe-bff7-4e6e-87f0-f4c44d038888::e127e16d-fbd9-48e5-a23e-0c7b1f75d270'
public_address = 'HcSCI338K5sAcavs867vIQrEJAz67twqq8HRk47oYQ97ucke3tyaPeYhVujfdfa'
test_agent = true

[[agents]]
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
keystore_file = '[UNUSED]'
name = 'arthur::e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a::e127e16d-fbd9-48e5-a23e-0c7b1f75d270'
public_address = 'HcScJYPwEJihs4ryagUKV96778KfqrKvf6BB8FesKDPu7wy8AujkO9xDn9vu9ez'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'arthur::fields::e127e16d-fbd9-48e5-a23e-0c7b1f75d270'
public_address = 'HcSCi7qYnBmzngxpxvufIZmX5dUbam648T7NOdCQm9vy7etb9tSXs5iU34Ftp9a'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'arthur::personalinformation::e127e16d-fbd9-48e5-a23e-0c7b1f75d270'
public_address = 'HcSCI5OIJFSs9bamyt59bZDVtgJas79vkRPr7JISO6hn9c5po3NOWc6ronpvcrr'
test_agent = true

[[agents]]
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
keystore_file = '[UNUSED]'
name = 'arthur::0098d2a1-5668-4a5a-8ef8-503d58dd38ce::e127e16d-fbd9-48e5-a23e-0c7b1f75d270'
public_address = 'HcScj6JqCt9DG4wejxcswNwgG94V3zzthP6In3i6xNm54P6x8ommVxPeV6jj7pi'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/projects/dna/dist/dna.dna.json'
hash = 'QmaHBVbQVeebMeGwHpa44wfB2wBYwBsCfrnHy7zfdHHbW3'
id = 'projects-test'
uuid = 'e127e16d-fbd9-48e5-a23e-0c7b1f75d270'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmNgqQPR4AfK6qAu1Ee36SgZB5hdFLvmmdmJ5DNVEdTS7r'
id = 'origins-test'
uuid = 'e127e16d-fbd9-48e5-a23e-0c7b1f75d270'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmX2zNDceP283yYnDZQEKCTVXdxXM2ydEWYTVna9BxvnVX'
id = 'kanban-test'
uuid = 'e127e16d-fbd9-48e5-a23e-0c7b1f75d270'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmYNPfDxsJ53Lv4jUr8fm1u3oah1QsgBndF5Z8rg96X1Uk'
id = 'notes-test'
uuid = 'e127e16d-fbd9-48e5-a23e-0c7b1f75d270'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmVp3peaRusBTz5Hib6j2xU9A4dDtkTfYzcm4PMpwn1LK4'
id = 'tasks-test'
uuid = 'e127e16d-fbd9-48e5-a23e-0c7b1f75d270'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmcusbVxHZwsTC2ccuHKZPUe4bGmsdHUvuWwE1YJhbxjeU'
id = 'fields-test'
uuid = 'e127e16d-fbd9-48e5-a23e-0c7b1f75d270'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmXKC8Q56mbvinRoVRcZp1XNrek8bCVQ3LxPEgQ4EJ4mdz'
id = 'personalinformation-test::cdf0afb7-380b-48d4-8910-02c25e953c04'
uuid = 'cdf0afb7-380b-48d4-8910-02c25e953c04::e127e16d-fbd9-48e5-a23e-0c7b1f75d270'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmXfaJ8ZjjTFvSKCZNuBj7QgMAqNHTFFi3HASXbqhajDaE'
id = 'freckles-test::3f0aa4d8-81bd-4f44-93af-007552748dac'
uuid = '3f0aa4d8-81bd-4f44-93af-007552748dac::e127e16d-fbd9-48e5-a23e-0c7b1f75d270'

[[instances]]
agent = 'ef5ba968-0048-4135-b831-a86b615a89b2'
dna = 'projects-test'
id = 'ef5ba968-0048-4135-b831-a86b615a89b2'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/tZRG5c/ef5ba968-0048-4135-b831-a86b615a89b2'
type = 'lmdb'

[[instances]]
agent = '57c01ed8-30ae-4fca-b6f9-40192821fed2'
dna = 'origins-test'
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/tZRG5c/57c01ed8-30ae-4fca-b6f9-40192821fed2'
type = 'lmdb'

[[instances]]
agent = '95569e2e-0de2-4073-8a7d-579f87534c04'
dna = 'kanban-test'
id = '95569e2e-0de2-4073-8a7d-579f87534c04'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/tZRG5c/95569e2e-0de2-4073-8a7d-579f87534c04'
type = 'lmdb'

[[instances]]
agent = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'
dna = 'notes-test'
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/tZRG5c/a23de7fe-bff7-4e6e-87f0-f4c44d038888'
type = 'lmdb'

[[instances]]
agent = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
dna = 'tasks-test'
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/tZRG5c/e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/tZRG5c/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::cdf0afb7-380b-48d4-8910-02c25e953c04'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/tZRG5c/personalinformation'
type = 'lmdb'

[[instances]]
agent = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
dna = 'freckles-test::3f0aa4d8-81bd-4f44-93af-007552748dac'
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/tZRG5c/0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'ef5ba968-0048-4135-b831-a86b615a89b2'

[[interfaces.instances]]
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'

[[interfaces.instances]]
id = '95569e2e-0de2-4073-8a7d-579f87534c04'

[[interfaces.instances]]
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'

[[interfaces.instances]]
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'

[interfaces.driver]
port = 33003
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
