bridges = []
persistence_dir = '/tmp/tmp.BQyMjyicr6/tryorama/XiG8VA'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'ef5ba968-0048-4135-b831-a86b615a89b2'
keystore_file = '[UNUSED]'
name = 'arthur::ef5ba968-0048-4135-b831-a86b615a89b2::00167667-2596-46a6-9360-838707a61def'
public_address = 'HcSCIQ7j9PESEabjfp7de4mIkiGpztw7yAntUmUTIowpjvutasjkd9qTpdsm5qr'
test_agent = true

[[agents]]
id = '95569e2e-0de2-4073-8a7d-579f87534c04'
keystore_file = '[UNUSED]'
name = 'arthur::95569e2e-0de2-4073-8a7d-579f87534c04::00167667-2596-46a6-9360-838707a61def'
public_address = 'HcSci3kC8mRaF6wiifpmPv9zn99w9ychqFeDM87ycnricr8yOTWo6Ns8yXfga6i'
test_agent = true

[[agents]]
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'
keystore_file = '[UNUSED]'
name = 'arthur::a23de7fe-bff7-4e6e-87f0-f4c44d038888::00167667-2596-46a6-9360-838707a61def'
public_address = 'HcSCIvHc8VP7ntdjhfOim8DDP8Rjk3heySJOWzC9U746Dgx8c4hO9MDMu66mdzz'
test_agent = true

[[agents]]
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
keystore_file = '[UNUSED]'
name = 'arthur::e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a::00167667-2596-46a6-9360-838707a61def'
public_address = 'HcSCi8afMxBK79ho3yx34aiJMCvV38md9Wx7ZQeCnQxmuaz9Bbfp865GM3oJawi'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'arthur::fields::00167667-2596-46a6-9360-838707a61def'
public_address = 'HcSCie5KRXySvkewbahNqpPbk5Dhxnktm5QhePPY98Krk9vzcBC7PHNvOgyg9sa'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'arthur::personalinformation::00167667-2596-46a6-9360-838707a61def'
public_address = 'HcScJ5mH9GeoUruerhMMKDSO3kz3cnjokzbiprJUPa49h33oKbv9ssqFtjjvtjz'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR-Holochain-redux/dna/crispr/dna/dist/dna.dna.json'
hash = 'QmUWSfFhe9mxP1GeMhy4VU8qUtZvG8vpnRKXwNTzppGGtg'
id = 'projects::4c2da543-6ab5-48e8-8d48-8ad1cb27a36a'
uuid = '4c2da543-6ab5-48e8-8d48-8ad1cb27a36a::00167667-2596-46a6-9360-838707a61def'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR-Holochain-redux/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmRwdkpeJKZUEQGf6pbxbf6gR8LTJqTtS3TRBGeB5FP4wn'
id = 'kanban::d7f3fa5e-a11f-46ba-8a62-8d6ece7abf8d'
uuid = 'd7f3fa5e-a11f-46ba-8a62-8d6ece7abf8d::00167667-2596-46a6-9360-838707a61def'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR-Holochain-redux/dna/notes/dna/dist/dna.dna.json'
hash = 'QmYsVvoCt9AJwfpKioxMNy1c4HxuhQH8uEmbhzVQG1YFvL'
id = 'notes::a7fb7fe1-3d85-44a3-bd24-f6e3fc12b43d'
uuid = 'a7fb7fe1-3d85-44a3-bd24-f6e3fc12b43d::00167667-2596-46a6-9360-838707a61def'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR-Holochain-redux/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmTz5DmDXna5qfcTvZzxmYBoqCrytu2j3s3Rw4fad9MMh7'
id = 'tasks::b66fb8ae-9812-46b6-8194-02fd7d188c78'
uuid = 'b66fb8ae-9812-46b6-8194-02fd7d188c78::00167667-2596-46a6-9360-838707a61def'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR-Holochain-redux/dna/curated_fields/dna/dist/dna.dna.json'
hash = 'QmbZLbdi2N5L62Fvnd9uTpGgAQk3yZiizmCLAtRnV5H7cr'
id = 'fields::49039c0b-25fb-4515-8800-c0ed79cd3dd9'
uuid = '49039c0b-25fb-4515-8800-c0ed79cd3dd9::00167667-2596-46a6-9360-838707a61def'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR-Holochain-redux/dna/personal_information/dna/dist/dna.dna.json'
hash = 'Qmbz7ZVDvSp481EKb3ZyR7qcVdqVGvaoSKtm4FxEUXNofu'
id = 'personalinformation::2b98b1a4-b34e-4ee2-bd1c-15a0d042c585'
uuid = '2b98b1a4-b34e-4ee2-bd1c-15a0d042c585::00167667-2596-46a6-9360-838707a61def'

[[instances]]
agent = 'ef5ba968-0048-4135-b831-a86b615a89b2'
dna = 'projects::4c2da543-6ab5-48e8-8d48-8ad1cb27a36a'
id = 'ef5ba968-0048-4135-b831-a86b615a89b2'

[instances.storage]
path = '/tmp/tmp.BQyMjyicr6/tryorama/XiG8VA/ef5ba968-0048-4135-b831-a86b615a89b2'
type = 'lmdb'

[[instances]]
agent = '95569e2e-0de2-4073-8a7d-579f87534c04'
dna = 'kanban::d7f3fa5e-a11f-46ba-8a62-8d6ece7abf8d'
id = '95569e2e-0de2-4073-8a7d-579f87534c04'

[instances.storage]
path = '/tmp/tmp.BQyMjyicr6/tryorama/XiG8VA/95569e2e-0de2-4073-8a7d-579f87534c04'
type = 'lmdb'

[[instances]]
agent = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'
dna = 'notes::a7fb7fe1-3d85-44a3-bd24-f6e3fc12b43d'
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'

[instances.storage]
path = '/tmp/tmp.BQyMjyicr6/tryorama/XiG8VA/a23de7fe-bff7-4e6e-87f0-f4c44d038888'
type = 'lmdb'

[[instances]]
agent = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
dna = 'tasks::b66fb8ae-9812-46b6-8194-02fd7d188c78'
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'

[instances.storage]
path = '/tmp/tmp.BQyMjyicr6/tryorama/XiG8VA/e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields::49039c0b-25fb-4515-8800-c0ed79cd3dd9'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.BQyMjyicr6/tryorama/XiG8VA/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation::2b98b1a4-b34e-4ee2-bd1c-15a0d042c585'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.BQyMjyicr6/tryorama/XiG8VA/personalinformation'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'developer-interface'

[[interfaces.instances]]
id = 'ef5ba968-0048-4135-b831-a86b615a89b2'

[[interfaces.instances]]
id = '95569e2e-0de2-4073-8a7d-579f87534c04'

[[interfaces.instances]]
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'

[[interfaces.instances]]
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[interfaces.driver]
port = 43003
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
