bridges = []
persistence_dir = '/tmp/tmp.sDlOw5C7Am/tryorama/eDWaYI'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'ef5ba968-0048-4135-b831-a86b615a89b2'
keystore_file = '[UNUSED]'
name = 'arthur::ef5ba968-0048-4135-b831-a86b615a89b2::07cc0b16-2c7c-4a3c-ab52-b987d432edba'
public_address = 'HcScidN6JQnxmheqsyoE9kBxHgOtdjykiqZezG8uVxpjpdsfBYiPHXpCsvomnwa'
test_agent = true

[[agents]]
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'
keystore_file = '[UNUSED]'
name = 'arthur::57c01ed8-30ae-4fca-b6f9-40192821fed2::07cc0b16-2c7c-4a3c-ab52-b987d432edba'
public_address = 'HcScjSSKu6zVmto33qeHyOMhzBved5pj8Z4ovIzafRd9h6h9m94y4F9zJYB7kra'
test_agent = true

[[agents]]
id = '95569e2e-0de2-4073-8a7d-579f87534c04'
keystore_file = '[UNUSED]'
name = 'arthur::95569e2e-0de2-4073-8a7d-579f87534c04::07cc0b16-2c7c-4a3c-ab52-b987d432edba'
public_address = 'HcSCio99t8wD5Xnx4z7n5QWQOyoQno7n9cYB3gGdPt7qo79a7aViW59dvNQzs3z'
test_agent = true

[[agents]]
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'
keystore_file = '[UNUSED]'
name = 'arthur::a23de7fe-bff7-4e6e-87f0-f4c44d038888::07cc0b16-2c7c-4a3c-ab52-b987d432edba'
public_address = 'HcSCJdi4eoHZfouh9e73SX7c5MT9jJ3v7eFYaOYFBtktdpk7745EXyX8IHO8ddr'
test_agent = true

[[agents]]
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
keystore_file = '[UNUSED]'
name = 'arthur::e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a::07cc0b16-2c7c-4a3c-ab52-b987d432edba'
public_address = 'HcSCjD6t5HAmizh3kxpQU8y8u4Ez6c6viGDS5MIROq8zyono5JhxjDEzWcwvrui'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'arthur::fields::07cc0b16-2c7c-4a3c-ab52-b987d432edba'
public_address = 'HcScJmVPYOpdruxmevH6mBn9Pdu7ma3n8mhCrSNOVwccayb3RWb3kXCR8Ox5r6i'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'arthur::personalinformation::07cc0b16-2c7c-4a3c-ab52-b987d432edba'
public_address = 'HcScJ7RgT9Rj9Ygqroz7e6ceWWiMsbynh8OYCijO4HVr99c8Ers46BUzkUgiwjz'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/projects/dna/dist/dna.dna.json'
hash = 'Qmb52iw7NSUN1rQxCDpHAYG4KPDXkJzk7Zf23gPyd5ZjNk'
id = 'projects-test::675f6af0-c7db-4c33-9130-bc1b4868e71c'
uuid = '675f6af0-c7db-4c33-9130-bc1b4868e71c::07cc0b16-2c7c-4a3c-ab52-b987d432edba'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmPRvQUUdqgsfgmdtqtfzE5G4L2TaPc2Jr3XMnFHuAwNzm'
id = 'origins-test::a2bb5882-9578-4c4d-9104-0c267614ee4e'
uuid = 'a2bb5882-9578-4c4d-9104-0c267614ee4e::07cc0b16-2c7c-4a3c-ab52-b987d432edba'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmPiUPJidVpyVduXyQZnWCTiHa4UKHmV9bSEHCoUDcZmaw'
id = 'kanban-test::35da932c-27ab-423d-a2d0-98406c0e6f9c'
uuid = '35da932c-27ab-423d-a2d0-98406c0e6f9c::07cc0b16-2c7c-4a3c-ab52-b987d432edba'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmRBfev7p8sKxEXTnGY2h9vv9mZfxrWeZqXJZccQSKqdxZ'
id = 'notes-test::96467e13-1f59-4c64-beeb-b12401c6ed61'
uuid = '96467e13-1f59-4c64-beeb-b12401c6ed61::07cc0b16-2c7c-4a3c-ab52-b987d432edba'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmRfrCqy6syHwe8RMBR64AUFuqwmDhaNquHK8FVCdVu34Y'
id = 'tasks-test::6e9545d3-3fca-4d1c-99b1-b96fad51b002'
uuid = '6e9545d3-3fca-4d1c-99b1-b96fad51b002::07cc0b16-2c7c-4a3c-ab52-b987d432edba'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmfFaosLNk27N4qjKX3hQBuVKhVB5Nq6PjC7HRZTn7QDST'
id = 'fields-test::3f047f19-bbc7-43ce-9acb-966460e5ef05'
uuid = '3f047f19-bbc7-43ce-9acb-966460e5ef05::07cc0b16-2c7c-4a3c-ab52-b987d432edba'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmajX6MyEWEi6YPEmZwfpUNHEZsXUJpTyZLgzNWGKxe6ar'
id = 'personalinformation-test::4d88d2eb-cddd-4ec8-bbc3-b5cdda3e81e2'
uuid = '4d88d2eb-cddd-4ec8-bbc3-b5cdda3e81e2::07cc0b16-2c7c-4a3c-ab52-b987d432edba'

[[instances]]
agent = 'ef5ba968-0048-4135-b831-a86b615a89b2'
dna = 'projects-test::675f6af0-c7db-4c33-9130-bc1b4868e71c'
id = 'ef5ba968-0048-4135-b831-a86b615a89b2'

[instances.storage]
path = '/tmp/tmp.sDlOw5C7Am/tryorama/eDWaYI/ef5ba968-0048-4135-b831-a86b615a89b2'
type = 'lmdb'

[[instances]]
agent = '57c01ed8-30ae-4fca-b6f9-40192821fed2'
dna = 'origins-test::a2bb5882-9578-4c4d-9104-0c267614ee4e'
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'

[instances.storage]
path = '/tmp/tmp.sDlOw5C7Am/tryorama/eDWaYI/57c01ed8-30ae-4fca-b6f9-40192821fed2'
type = 'lmdb'

[[instances]]
agent = '95569e2e-0de2-4073-8a7d-579f87534c04'
dna = 'kanban-test::35da932c-27ab-423d-a2d0-98406c0e6f9c'
id = '95569e2e-0de2-4073-8a7d-579f87534c04'

[instances.storage]
path = '/tmp/tmp.sDlOw5C7Am/tryorama/eDWaYI/95569e2e-0de2-4073-8a7d-579f87534c04'
type = 'lmdb'

[[instances]]
agent = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'
dna = 'notes-test::96467e13-1f59-4c64-beeb-b12401c6ed61'
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'

[instances.storage]
path = '/tmp/tmp.sDlOw5C7Am/tryorama/eDWaYI/a23de7fe-bff7-4e6e-87f0-f4c44d038888'
type = 'lmdb'

[[instances]]
agent = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
dna = 'tasks-test::6e9545d3-3fca-4d1c-99b1-b96fad51b002'
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'

[instances.storage]
path = '/tmp/tmp.sDlOw5C7Am/tryorama/eDWaYI/e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test::3f047f19-bbc7-43ce-9acb-966460e5ef05'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.sDlOw5C7Am/tryorama/eDWaYI/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::4d88d2eb-cddd-4ec8-bbc3-b5cdda3e81e2'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.sDlOw5C7Am/tryorama/eDWaYI/personalinformation'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'ef5ba968-0048-4135-b831-a86b615a89b2'

[[interfaces.instances]]
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'

[[interfaces.instances]]
id = '95569e2e-0de2-4073-8a7d-579f87534c04'

[[interfaces.instances]]
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'

[[interfaces.instances]]
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[interfaces.driver]
port = 33003
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
