bridges = []
persistence_dir = '/tmp/tmp.1KXds5iZNc/tryorama/FXu1TT'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = '95569e2e-0de2-4073-8a7d-579f87534c04'
keystore_file = '[UNUSED]'
name = 'alice::95569e2e-0de2-4073-8a7d-579f87534c04::9a5f1c37-51cc-4213-ba34-0e5bca522bc8'
public_address = 'HcScJXe94XstEf6fjvWrpheIuhzm9oyso74YdXnqUj3ksbt8MbHqawwJtehvx3a'
test_agent = true

[[agents]]
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'
keystore_file = '[UNUSED]'
name = 'alice::a23de7fe-bff7-4e6e-87f0-f4c44d038888::9a5f1c37-51cc-4213-ba34-0e5bca522bc8'
public_address = 'HcScJheY9deF5kihp9HFf6Ui6r65i97qiD3GCdd75y9kzyzefGMo5JRB3Wxkoir'
test_agent = true

[[agents]]
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
keystore_file = '[UNUSED]'
name = 'alice::e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a::9a5f1c37-51cc-4213-ba34-0e5bca522bc8'
public_address = 'HcSCjDdHcM95I399da4aKNOeEZ3opti7bwKh79IcRjF83kmhkXTUc3BFDuzrqjz'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'alice::fields::9a5f1c37-51cc-4213-ba34-0e5bca522bc8'
public_address = 'HcScjx4rI7983YzPnzyN8evc5yfsmdf4ggq4VBpXQK8eccx5GsmEvKXHrav8aua'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'alice::personalinformation::9a5f1c37-51cc-4213-ba34-0e5bca522bc8'
public_address = 'HcScJFP944eBQVomeeUyfYwwt6zcydi4wkeZtF9VJcypcdwkbEfBti5t4Anzpcr'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmechRHjCEkfvuDDDVhxMAyEUaqngzBpndnPM2LC4At4D1'
id = 'kanban::9e448913-e88c-4d77-bec5-9f58197b16e1'
uuid = '9e448913-e88c-4d77-bec5-9f58197b16e1::9a5f1c37-51cc-4213-ba34-0e5bca522bc8'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmVdkArkF7wTGiQ9j6tbrtrefUZezqtyqsRaXSarvG2CmG'
id = 'notes::f38f175e-0ed9-4a27-be5f-ece5a7a568a4'
uuid = 'f38f175e-0ed9-4a27-be5f-ece5a7a568a4::9a5f1c37-51cc-4213-ba34-0e5bca522bc8'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmU5BDQTV2K1zWv8FfBU1ajx9vMnjLNqmZJu3H2pXuXJo2'
id = 'tasks::fe7ab10c-ba2c-44eb-a04a-34f3925e0e53'
uuid = 'fe7ab10c-ba2c-44eb-a04a-34f3925e0e53::9a5f1c37-51cc-4213-ba34-0e5bca522bc8'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curated_fields/dna/dist/dna.dna.json'
hash = 'QmT93QEMFFyyYHDMan6KnSukqL8MD5pP3r53SkDxAxgqBA'
id = 'fields::8d334630-e9f1-4a02-9282-2ab8bb6ca940'
uuid = '8d334630-e9f1-4a02-9282-2ab8bb6ca940::9a5f1c37-51cc-4213-ba34-0e5bca522bc8'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personal_information/dna/dist/dna.dna.json'
hash = 'QmSDh3AHtuHjRUr2Qwm5FWmkZYUKCRLzCWkZ9b1sSvsmB6'
id = 'personalinformation::8595699b-6186-49c1-a02b-bebf6cf5ee03'
uuid = '8595699b-6186-49c1-a02b-bebf6cf5ee03::9a5f1c37-51cc-4213-ba34-0e5bca522bc8'

[[instances]]
agent = '95569e2e-0de2-4073-8a7d-579f87534c04'
dna = 'kanban::9e448913-e88c-4d77-bec5-9f58197b16e1'
id = '95569e2e-0de2-4073-8a7d-579f87534c04'

[instances.storage]
path = '/tmp/tmp.1KXds5iZNc/tryorama/FXu1TT/95569e2e-0de2-4073-8a7d-579f87534c04'
type = 'lmdb'

[[instances]]
agent = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'
dna = 'notes::f38f175e-0ed9-4a27-be5f-ece5a7a568a4'
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'

[instances.storage]
path = '/tmp/tmp.1KXds5iZNc/tryorama/FXu1TT/a23de7fe-bff7-4e6e-87f0-f4c44d038888'
type = 'lmdb'

[[instances]]
agent = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
dna = 'tasks::fe7ab10c-ba2c-44eb-a04a-34f3925e0e53'
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'

[instances.storage]
path = '/tmp/tmp.1KXds5iZNc/tryorama/FXu1TT/e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields::8d334630-e9f1-4a02-9282-2ab8bb6ca940'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.1KXds5iZNc/tryorama/FXu1TT/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation::8595699b-6186-49c1-a02b-bebf6cf5ee03'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.1KXds5iZNc/tryorama/FXu1TT/personalinformation'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = '95569e2e-0de2-4073-8a7d-579f87534c04'

[[interfaces.instances]]
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'

[[interfaces.instances]]
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[interfaces.driver]
port = 33004
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
