bridges = []
persistence_dir = '/tmp/tmp.BQyMjyicr6/tryorama/YFqxWY'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = '95569e2e-0de2-4073-8a7d-579f87534c04'
keystore_file = '[UNUSED]'
name = 'alice::95569e2e-0de2-4073-8a7d-579f87534c04::00167667-2596-46a6-9360-838707a61def'
public_address = 'HcSCJ8tMTE34Ci7axpfUfSUbPn73a7dtx5Ub3IMCBGetv4weYVVvenhtf8uprbr'
test_agent = true

[[agents]]
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'
keystore_file = '[UNUSED]'
name = 'alice::a23de7fe-bff7-4e6e-87f0-f4c44d038888::00167667-2596-46a6-9360-838707a61def'
public_address = 'HcSCjYfZ3gKDpwjv6cmKfbEP3vAyfrydd8ZIdVNeXismcey4R485ert5CTBdegr'
test_agent = true

[[agents]]
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
keystore_file = '[UNUSED]'
name = 'alice::e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a::00167667-2596-46a6-9360-838707a61def'
public_address = 'HcSCjWmfuzOs6axbp3h58UKpWUx4mh8rstYKGOiAoiahh87aOX8AeBFtRixej3i'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'alice::fields::00167667-2596-46a6-9360-838707a61def'
public_address = 'HcSCi93Vk6CsF7q54ww5MAdNvXG7ovv3oOZWtfVowp5x4vpidaAbSF3ZYhyrffr'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'alice::personalinformation::00167667-2596-46a6-9360-838707a61def'
public_address = 'HcScIhtiOxPy4icugrYUWePMam7cpvyg9O7WhoisH6umh8ckGN73yBdk8wegwsr'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR-Holochain-redux/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmRwdkpeJKZUEQGf6pbxbf6gR8LTJqTtS3TRBGeB5FP4wn'
id = 'kanban::d7f3fa5e-a11f-46ba-8a62-8d6ece7abf8d'
uuid = 'd7f3fa5e-a11f-46ba-8a62-8d6ece7abf8d::00167667-2596-46a6-9360-838707a61def'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR-Holochain-redux/dna/notes/dna/dist/dna.dna.json'
hash = 'QmYsVvoCt9AJwfpKioxMNy1c4HxuhQH8uEmbhzVQG1YFvL'
id = 'notes::a7fb7fe1-3d85-44a3-bd24-f6e3fc12b43d'
uuid = 'a7fb7fe1-3d85-44a3-bd24-f6e3fc12b43d::00167667-2596-46a6-9360-838707a61def'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR-Holochain-redux/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmTz5DmDXna5qfcTvZzxmYBoqCrytu2j3s3Rw4fad9MMh7'
id = 'tasks::b66fb8ae-9812-46b6-8194-02fd7d188c78'
uuid = 'b66fb8ae-9812-46b6-8194-02fd7d188c78::00167667-2596-46a6-9360-838707a61def'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR-Holochain-redux/dna/curated_fields/dna/dist/dna.dna.json'
hash = 'QmbZLbdi2N5L62Fvnd9uTpGgAQk3yZiizmCLAtRnV5H7cr'
id = 'fields::49039c0b-25fb-4515-8800-c0ed79cd3dd9'
uuid = '49039c0b-25fb-4515-8800-c0ed79cd3dd9::00167667-2596-46a6-9360-838707a61def'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR-Holochain-redux/dna/personal_information/dna/dist/dna.dna.json'
hash = 'QmbXiTbBSDwZNB9QEAEsGoYiohxby4gRfVbNTW3VkuQCNW'
id = 'personalinformation::37cd19a1-b372-4fd4-84c5-c8e5d4a77c06'
uuid = '37cd19a1-b372-4fd4-84c5-c8e5d4a77c06::00167667-2596-46a6-9360-838707a61def'

[[instances]]
agent = '95569e2e-0de2-4073-8a7d-579f87534c04'
dna = 'kanban::d7f3fa5e-a11f-46ba-8a62-8d6ece7abf8d'
id = '95569e2e-0de2-4073-8a7d-579f87534c04'

[instances.storage]
path = '/tmp/tmp.BQyMjyicr6/tryorama/YFqxWY/95569e2e-0de2-4073-8a7d-579f87534c04'
type = 'lmdb'

[[instances]]
agent = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'
dna = 'notes::a7fb7fe1-3d85-44a3-bd24-f6e3fc12b43d'
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'

[instances.storage]
path = '/tmp/tmp.BQyMjyicr6/tryorama/YFqxWY/a23de7fe-bff7-4e6e-87f0-f4c44d038888'
type = 'lmdb'

[[instances]]
agent = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
dna = 'tasks::b66fb8ae-9812-46b6-8194-02fd7d188c78'
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'

[instances.storage]
path = '/tmp/tmp.BQyMjyicr6/tryorama/YFqxWY/e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields::49039c0b-25fb-4515-8800-c0ed79cd3dd9'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.BQyMjyicr6/tryorama/YFqxWY/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation::37cd19a1-b372-4fd4-84c5-c8e5d4a77c06'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.BQyMjyicr6/tryorama/YFqxWY/personalinformation'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'developer-interface'

[[interfaces.instances]]
id = '95569e2e-0de2-4073-8a7d-579f87534c04'

[[interfaces.instances]]
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'

[[interfaces.instances]]
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[interfaces.driver]
port = 43004
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
