bridges = []
persistence_dir = '/tmp/tmp.OGr2YY1n4S/tryorama/HU3Q9z'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'
keystore_file = '[UNUSED]'
name = 'alice::57c01ed8-30ae-4fca-b6f9-40192821fed2::03ee7700-bc2f-4695-b0bd-a0644f2b5491'
public_address = 'HcSCiD8gySY4FgocjiqDaWVU5nf99pywvmKQSp5ouFs5a8hnwqMw3374K6UO3na'
test_agent = true

[[agents]]
id = '95569e2e-0de2-4073-8a7d-579f87534c04'
keystore_file = '[UNUSED]'
name = 'alice::95569e2e-0de2-4073-8a7d-579f87534c04::03ee7700-bc2f-4695-b0bd-a0644f2b5491'
public_address = 'HcSCIx9Gngwn3ejyfywhffOP6g8Iby7axI4Rhd3Fc7ytdgf9yk3A4V66Rtbsqfz'
test_agent = true

[[agents]]
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'
keystore_file = '[UNUSED]'
name = 'alice::a23de7fe-bff7-4e6e-87f0-f4c44d038888::03ee7700-bc2f-4695-b0bd-a0644f2b5491'
public_address = 'HcSciWnYQtRtrfegr7T4IzkDK4h4N8i37R8zU8VChjhxgzh37YVMVKDMQk4piaa'
test_agent = true

[[agents]]
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
keystore_file = '[UNUSED]'
name = 'alice::e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a::03ee7700-bc2f-4695-b0bd-a0644f2b5491'
public_address = 'HcScIj9Ux743SrOwq8cTO4cKhQ5wugyjkiPv3aKUTFcmsxagxYjtYO5tKzteyda'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'alice::fields::03ee7700-bc2f-4695-b0bd-a0644f2b5491'
public_address = 'HcSCiUeh83ecPma7znihR8o9vrqhic64voTcF9y7DoH555mbS75Zo6ZkGH3Mcja'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'alice::personalinformation::03ee7700-bc2f-4695-b0bd-a0644f2b5491'
public_address = 'HcScidn79pP7itie8iNBtAki5uHic7aeu3E7VNX3jGbTd356bxXw9DiUD767n8r'
test_agent = true

[[agents]]
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
keystore_file = '[UNUSED]'
name = 'alice::0098d2a1-5668-4a5a-8ef8-503d58dd38ce::03ee7700-bc2f-4695-b0bd-a0644f2b5491'
public_address = 'HcScI9iCpAchn6y7648Xi9UpguBGpe4xs4KKwUgc8I4dwyw5jPt9DaR3nqx8sqi'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmWkTN4HSPwWSLp9jY1TWVD7QSenhFfbHh8AZWkeGhPptr'
id = 'origins-test'
uuid = '03ee7700-bc2f-4695-b0bd-a0644f2b5491'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmW5g3BMZsXcvWZuiy5ZE2oaMM7VkmdqRmGu3wb8JYx1eB'
id = 'kanban-test'
uuid = '03ee7700-bc2f-4695-b0bd-a0644f2b5491'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmYtxfVo45KLBQfE8ke5ohLxTTn5dRMaVorSsgP1qXJuXU'
id = 'notes-test'
uuid = '03ee7700-bc2f-4695-b0bd-a0644f2b5491'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmRRAYzmWFk3ZCRaa5ZE3HFV9hqhF5AYT4LxzaP7fufD95'
id = 'tasks-test'
uuid = '03ee7700-bc2f-4695-b0bd-a0644f2b5491'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmTDiSCfDE66C1Hd6KA7pakAYb5DJrzNsP1NqC6DJvKqKy'
id = 'fields-test'
uuid = '03ee7700-bc2f-4695-b0bd-a0644f2b5491'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmT5Eh8v3wzrTHaQywAEjJVTgsmPzwnvUt8fk7teDLsVsP'
id = 'personalinformation-test::b08e9df2-c716-49ec-956e-c53e5513df55'
uuid = 'b08e9df2-c716-49ec-956e-c53e5513df55::03ee7700-bc2f-4695-b0bd-a0644f2b5491'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmZWZVComxfZfgQFGmgHLRnJpz5RW4hJXfZbQHgreYqgcv'
id = 'freckles-test::c2c32c08-d13e-489c-9097-be3b4477fc9b'
uuid = 'c2c32c08-d13e-489c-9097-be3b4477fc9b::03ee7700-bc2f-4695-b0bd-a0644f2b5491'

[[instances]]
agent = '57c01ed8-30ae-4fca-b6f9-40192821fed2'
dna = 'origins-test'
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/HU3Q9z/57c01ed8-30ae-4fca-b6f9-40192821fed2'
type = 'lmdb'

[[instances]]
agent = '95569e2e-0de2-4073-8a7d-579f87534c04'
dna = 'kanban-test'
id = '95569e2e-0de2-4073-8a7d-579f87534c04'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/HU3Q9z/95569e2e-0de2-4073-8a7d-579f87534c04'
type = 'lmdb'

[[instances]]
agent = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'
dna = 'notes-test'
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/HU3Q9z/a23de7fe-bff7-4e6e-87f0-f4c44d038888'
type = 'lmdb'

[[instances]]
agent = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
dna = 'tasks-test'
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/HU3Q9z/e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/HU3Q9z/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::b08e9df2-c716-49ec-956e-c53e5513df55'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/HU3Q9z/personalinformation'
type = 'lmdb'

[[instances]]
agent = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
dna = 'freckles-test::c2c32c08-d13e-489c-9097-be3b4477fc9b'
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/HU3Q9z/0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'

[[interfaces.instances]]
id = '95569e2e-0de2-4073-8a7d-579f87534c04'

[[interfaces.instances]]
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'

[[interfaces.instances]]
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'

[interfaces.driver]
port = 33004
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
