bridges = []
persistence_dir = '/tmp/tmp.BQyMjyicr6/tryorama/4kYhmo'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = '95569e2e-0de2-4073-8a7d-579f87534c04'
keystore_file = '[UNUSED]'
name = 'alice::95569e2e-0de2-4073-8a7d-579f87534c04::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'
public_address = 'HcSciUWGRXmn3e53htQvzK8dtZwhof5k5DTtGxdP9Ddpouq56aSeSJAb3rc8rbr'
test_agent = true

[[agents]]
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'
keystore_file = '[UNUSED]'
name = 'alice::a23de7fe-bff7-4e6e-87f0-f4c44d038888::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'
public_address = 'HcScJ5cREN9Hmewx33ntbij9sAHwnuphzV3tnCiRYzj84cwiNCruPryYycizrti'
test_agent = true

[[agents]]
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
keystore_file = '[UNUSED]'
name = 'alice::e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'
public_address = 'HcScjaqRYaxpknqn7vYDCG3dBrpvg8casCNxbN3toMfjrcg7he5D5BO3iNqqhtz'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'alice::fields::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'
public_address = 'HcScIWqxuMz3mxucww9v7eK7qiuwbc96ii3gH7oiJ88PNejdkqY4ZXW8pfz3hga'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'alice::personalinformation::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'
public_address = 'HcScIPG47h5K4THrzsGoIrM3pzDkd35o8mBsu9wpeku8dtod75kO4MK3jtoBegi'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR-Holochain-redux/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmejcBj2Zr2Rog9dAk4xBZKdSVgCZhig1TgiePWh9exam8'
id = 'kanban::d5199a30-2b6e-4756-b6ef-84fc1c5422b1'
uuid = 'd5199a30-2b6e-4756-b6ef-84fc1c5422b1::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR-Holochain-redux/dna/notes/dna/dist/dna.dna.json'
hash = 'QmdJ3DS3g3PZwXZtB4VRNhxwbgHCZQ1GGdxF65LBfjrWjs'
id = 'notes::c78a9590-c57b-4750-9ca2-b73c53a01110'
uuid = 'c78a9590-c57b-4750-9ca2-b73c53a01110::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR-Holochain-redux/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmWjVjtrfovwbJseu72kzLijqpo1yMU3xSjNHetULqVPWe'
id = 'tasks::c48b7988-bccd-431b-b72a-60331fbcedbb'
uuid = 'c48b7988-bccd-431b-b72a-60331fbcedbb::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR-Holochain-redux/dna/curated_fields/dna/dist/dna.dna.json'
hash = 'QmZBy9hXpDEcnr43wV6CrEGb4GhwhpUeBTJ3U2avPCmnX2'
id = 'fields::96960c3f-1036-4e6a-96f1-ef2eebb57f41'
uuid = '96960c3f-1036-4e6a-96f1-ef2eebb57f41::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR-Holochain-redux/dna/personal_information/dna/dist/dna.dna.json'
hash = 'QmYxKuvYpL28dtMKfjVrP7dw8qTEzRcBqoVxncz3ApQ4Yg'
id = 'personalinformation::3f481564-0f98-4706-8627-9a0588b12fde'
uuid = '3f481564-0f98-4706-8627-9a0588b12fde::e54ce24b-88e2-40f9-b4f5-7b41d54a13e3'

[[instances]]
agent = '95569e2e-0de2-4073-8a7d-579f87534c04'
dna = 'kanban::d5199a30-2b6e-4756-b6ef-84fc1c5422b1'
id = '95569e2e-0de2-4073-8a7d-579f87534c04'

[instances.storage]
path = '/tmp/tmp.BQyMjyicr6/tryorama/4kYhmo/95569e2e-0de2-4073-8a7d-579f87534c04'
type = 'lmdb'

[[instances]]
agent = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'
dna = 'notes::c78a9590-c57b-4750-9ca2-b73c53a01110'
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'

[instances.storage]
path = '/tmp/tmp.BQyMjyicr6/tryorama/4kYhmo/a23de7fe-bff7-4e6e-87f0-f4c44d038888'
type = 'lmdb'

[[instances]]
agent = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
dna = 'tasks::c48b7988-bccd-431b-b72a-60331fbcedbb'
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'

[instances.storage]
path = '/tmp/tmp.BQyMjyicr6/tryorama/4kYhmo/e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields::96960c3f-1036-4e6a-96f1-ef2eebb57f41'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.BQyMjyicr6/tryorama/4kYhmo/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation::3f481564-0f98-4706-8627-9a0588b12fde'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.BQyMjyicr6/tryorama/4kYhmo/personalinformation'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'developer-interface'

[[interfaces.instances]]
id = '95569e2e-0de2-4073-8a7d-579f87534c04'

[[interfaces.instances]]
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'

[[interfaces.instances]]
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[interfaces.driver]
port = 43004
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
