bridges = []
persistence_dir = '/tmp/tmp.1KXds5iZNc/tryorama/eSPyOW'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'ef5ba968-0048-4135-b831-a86b615a89b2'
keystore_file = '[UNUSED]'
name = 'mark::ef5ba968-0048-4135-b831-a86b615a89b2::9a5f1c37-51cc-4213-ba34-0e5bca522bc8'
public_address = 'HcSCJYNkqJVn64hdngos9C3WWtOg3jdoyJO5A85KT3M4eQ7qQpWSgHPtrtj7zqr'
test_agent = true

[[agents]]
id = '95569e2e-0de2-4073-8a7d-579f87534c04'
keystore_file = '[UNUSED]'
name = 'mark::95569e2e-0de2-4073-8a7d-579f87534c04::9a5f1c37-51cc-4213-ba34-0e5bca522bc8'
public_address = 'HcScj9QT4Grz7Y85b333AKEG3cYZsfpnctGI5OrH5qf9t3gbkadTF9sx4d9bdti'
test_agent = true

[[agents]]
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'
keystore_file = '[UNUSED]'
name = 'mark::a23de7fe-bff7-4e6e-87f0-f4c44d038888::9a5f1c37-51cc-4213-ba34-0e5bca522bc8'
public_address = 'HcSCip69pou5MerbsiDAWNFaNfrrfszduk99zFGma5E8jxhbt7Mqpvpgds765vz'
test_agent = true

[[agents]]
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
keystore_file = '[UNUSED]'
name = 'mark::e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a::9a5f1c37-51cc-4213-ba34-0e5bca522bc8'
public_address = 'HcSCIHe3qzux7z4nxija63yCkqOArxvviJwq3Qxjj55t5g4fW6UyW8Z5S6QOa9r'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'mark::fields::9a5f1c37-51cc-4213-ba34-0e5bca522bc8'
public_address = 'HcSci4kwwzzpq5s3kuz96p6I6mgN8nykdIxfnGtfE7oh77qbZ8kBB8CNyKeyysa'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'mark::personalinformation::9a5f1c37-51cc-4213-ba34-0e5bca522bc8'
public_address = 'HcSCJT49P97MuPsjn7U8J3SWqz4hvgh65wiZ6vsk8Epxy5inAnxOa3OB4hfj7ua'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/crispr/dna/dist/dna.dna.json'
hash = 'QmcvVEgVhtghgr6Y7PVVwKEmqbnh5bTRMaFL1VfKw9gRNN'
id = 'projects::486edca1-e033-41ca-b01d-4b9587ad642a'
uuid = '486edca1-e033-41ca-b01d-4b9587ad642a::9a5f1c37-51cc-4213-ba34-0e5bca522bc8'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmechRHjCEkfvuDDDVhxMAyEUaqngzBpndnPM2LC4At4D1'
id = 'kanban::9e448913-e88c-4d77-bec5-9f58197b16e1'
uuid = '9e448913-e88c-4d77-bec5-9f58197b16e1::9a5f1c37-51cc-4213-ba34-0e5bca522bc8'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmVdkArkF7wTGiQ9j6tbrtrefUZezqtyqsRaXSarvG2CmG'
id = 'notes::f38f175e-0ed9-4a27-be5f-ece5a7a568a4'
uuid = 'f38f175e-0ed9-4a27-be5f-ece5a7a568a4::9a5f1c37-51cc-4213-ba34-0e5bca522bc8'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'QmU5BDQTV2K1zWv8FfBU1ajx9vMnjLNqmZJu3H2pXuXJo2'
id = 'tasks::fe7ab10c-ba2c-44eb-a04a-34f3925e0e53'
uuid = 'fe7ab10c-ba2c-44eb-a04a-34f3925e0e53::9a5f1c37-51cc-4213-ba34-0e5bca522bc8'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curated_fields/dna/dist/dna.dna.json'
hash = 'QmT93QEMFFyyYHDMan6KnSukqL8MD5pP3r53SkDxAxgqBA'
id = 'fields::8d334630-e9f1-4a02-9282-2ab8bb6ca940'
uuid = '8d334630-e9f1-4a02-9282-2ab8bb6ca940::9a5f1c37-51cc-4213-ba34-0e5bca522bc8'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personal_information/dna/dist/dna.dna.json'
hash = 'QmUCwyHKDfqHg7fbz9k9vxwzyyLVGS5C98yT4ULK2U2oBX'
id = 'personalinformation::ae7aeabd-57b7-48db-8a7a-79237bfedaf3'
uuid = 'ae7aeabd-57b7-48db-8a7a-79237bfedaf3::9a5f1c37-51cc-4213-ba34-0e5bca522bc8'

[[instances]]
agent = 'ef5ba968-0048-4135-b831-a86b615a89b2'
dna = 'projects::486edca1-e033-41ca-b01d-4b9587ad642a'
id = 'ef5ba968-0048-4135-b831-a86b615a89b2'

[instances.storage]
path = '/tmp/tmp.1KXds5iZNc/tryorama/eSPyOW/ef5ba968-0048-4135-b831-a86b615a89b2'
type = 'lmdb'

[[instances]]
agent = '95569e2e-0de2-4073-8a7d-579f87534c04'
dna = 'kanban::9e448913-e88c-4d77-bec5-9f58197b16e1'
id = '95569e2e-0de2-4073-8a7d-579f87534c04'

[instances.storage]
path = '/tmp/tmp.1KXds5iZNc/tryorama/eSPyOW/95569e2e-0de2-4073-8a7d-579f87534c04'
type = 'lmdb'

[[instances]]
agent = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'
dna = 'notes::f38f175e-0ed9-4a27-be5f-ece5a7a568a4'
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'

[instances.storage]
path = '/tmp/tmp.1KXds5iZNc/tryorama/eSPyOW/a23de7fe-bff7-4e6e-87f0-f4c44d038888'
type = 'lmdb'

[[instances]]
agent = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
dna = 'tasks::fe7ab10c-ba2c-44eb-a04a-34f3925e0e53'
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'

[instances.storage]
path = '/tmp/tmp.1KXds5iZNc/tryorama/eSPyOW/e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields::8d334630-e9f1-4a02-9282-2ab8bb6ca940'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.1KXds5iZNc/tryorama/eSPyOW/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation::ae7aeabd-57b7-48db-8a7a-79237bfedaf3'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.1KXds5iZNc/tryorama/eSPyOW/personalinformation'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'ef5ba968-0048-4135-b831-a86b615a89b2'

[[interfaces.instances]]
id = '95569e2e-0de2-4073-8a7d-579f87534c04'

[[interfaces.instances]]
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'

[[interfaces.instances]]
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[interfaces.driver]
port = 33005
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
