bridges = []
persistence_dir = '/tmp/tmp.OGr2YY1n4S/tryorama/WnhPtW'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'ef5ba968-0048-4135-b831-a86b615a89b2'
keystore_file = '[UNUSED]'
name = 'mark::ef5ba968-0048-4135-b831-a86b615a89b2::882a0bdf-1be0-41bd-94a9-88d6c0272e8a'
public_address = 'HcSCIci3ICh6xs873wU7HqWDeS6ur7db94itrnhhVxqcpykuqr7bSVUbYm8hmuz'
test_agent = true

[[agents]]
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'
keystore_file = '[UNUSED]'
name = 'mark::57c01ed8-30ae-4fca-b6f9-40192821fed2::882a0bdf-1be0-41bd-94a9-88d6c0272e8a'
public_address = 'HcSCJzDiteSvrq9xgi7QH66ODZVPJi9izUpBvqAD73XgzojzO6E8vZhXTSs6acr'
test_agent = true

[[agents]]
id = '164449a2-e7d4-47dc-acc8-2fe317b8d9fe'
keystore_file = '[UNUSED]'
name = 'mark::164449a2-e7d4-47dc-acc8-2fe317b8d9fe::882a0bdf-1be0-41bd-94a9-88d6c0272e8a'
public_address = 'HcScj5ykCOpfwjqu7y3i3JYRIsx9Sy4b5SGF38i9Z5qvvsgp45gGHz6UXNaaz8z'
test_agent = true

[[agents]]
id = '95569e2e-0de2-4073-8a7d-579f87534c04'
keystore_file = '[UNUSED]'
name = 'mark::95569e2e-0de2-4073-8a7d-579f87534c04::882a0bdf-1be0-41bd-94a9-88d6c0272e8a'
public_address = 'HcSci35zFDx59EQb6y5WDrhWOT4Bhbzbam3AcvZs8Scbhb9k3rQ9Mdv5nDTtzoa'
test_agent = true

[[agents]]
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'
keystore_file = '[UNUSED]'
name = 'mark::a23de7fe-bff7-4e6e-87f0-f4c44d038888::882a0bdf-1be0-41bd-94a9-88d6c0272e8a'
public_address = 'HcSCijqr3xjbbggjp5kE8yh6Doqzstxg86Vpd9Z9bxvIqwnte6UsnQ7oXJ76i3r'
test_agent = true

[[agents]]
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
keystore_file = '[UNUSED]'
name = 'mark::e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a::882a0bdf-1be0-41bd-94a9-88d6c0272e8a'
public_address = 'HcScI7ukKIS6Mvc4jz9i43pxjS5IfA9fq7gO7HY84grevh8i5OJIo6yy9Jx5amr'
test_agent = true

[[agents]]
id = 'fields'
keystore_file = '[UNUSED]'
name = 'mark::fields::882a0bdf-1be0-41bd-94a9-88d6c0272e8a'
public_address = 'HcScJ3gmQFka7tsvu9iAAgjzqvd9jkj7mpnPp5fTTOa5ecxdj887xz3NYgU8Rwi'
test_agent = true

[[agents]]
id = 'personalinformation'
keystore_file = '[UNUSED]'
name = 'mark::personalinformation::882a0bdf-1be0-41bd-94a9-88d6c0272e8a'
public_address = 'HcScizvBogT5r578ijWTXn57SmNPw7b3jd4AXb6WA9Z7VpfhrR5M4d9oZcJshma'
test_agent = true

[[agents]]
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
keystore_file = '[UNUSED]'
name = 'mark::0098d2a1-5668-4a5a-8ef8-503d58dd38ce::882a0bdf-1be0-41bd-94a9-88d6c0272e8a'
public_address = 'HcSCJF8kHawOvnd6md3Xq4oA74X4RUX8s9w5aPrH3VHjgz9p34DWzPpoUAmt9xi'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/projects/dna/dist/dna.dna.json'
hash = 'QmbzE3wfY3kDjCYcm8P7GGDL25CmawpFvtNeHW24ZKR4PY'
id = 'projects-test::09e3dd55-68f5-4df4-9866-8e8107c22276'
uuid = '09e3dd55-68f5-4df4-9866-8e8107c22276::882a0bdf-1be0-41bd-94a9-88d6c0272e8a'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmRPh9uMn158vqPriMHRTbAT7gL13zX4CNF9uAHhQpsymQ'
id = 'origins-test::14005bc1-f5b9-434d-8e05-23188c3813f6'
uuid = '14005bc1-f5b9-434d-8e05-23188c3813f6::882a0bdf-1be0-41bd-94a9-88d6c0272e8a'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/origins/dna/dist/dna.dna.json'
hash = 'QmVeBTt4ujdrzyL6rKczKa3AhDnWFvh8ftxdVqXBuA8BwC'
id = 'origins-test::48e7f196-93f4-4514-9994-ffd27512bd36'
uuid = '48e7f196-93f4-4514-9994-ffd27512bd36::882a0bdf-1be0-41bd-94a9-88d6c0272e8a'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/kanban/dna/dist/dna.dna.json'
hash = 'QmQ1aGVMMGhYiFECdiFwxpj9dppFJHWaYSPgvoFVMHyxGJ'
id = 'kanban-test::5b8b5157-ee45-4016-aa06-5f0f44fbfc65'
uuid = '5b8b5157-ee45-4016-aa06-5f0f44fbfc65::882a0bdf-1be0-41bd-94a9-88d6c0272e8a'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/notes/dna/dist/dna.dna.json'
hash = 'QmWJomnmdSFAqW2KBmgNZduchF3EKEepwY9jB4PPvJdZiq'
id = 'notes-test::310601c6-a594-4ce7-a21f-5c97d5e7ce41'
uuid = '310601c6-a594-4ce7-a21f-5c97d5e7ce41::882a0bdf-1be0-41bd-94a9-88d6c0272e8a'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/tasks/dna/dist/dna.dna.json'
hash = 'Qmb3P3TmiydCj3gJbv12jXNbSwYmR7awZM21aw6B6h8H7Z'
id = 'tasks-test::edbb4b96-7768-47ad-b9a7-bdb31462225d'
uuid = 'edbb4b96-7768-47ad-b9a7-bdb31462225d::882a0bdf-1be0-41bd-94a9-88d6c0272e8a'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/curatedfields/dna/dist/dna.dna.json'
hash = 'QmaB5T8szdmQ414JNzRBGUoPt7qjt5GmoZR6YXptkFvNqY'
id = 'fields-test::b1d9769d-94a8-427d-8ec6-fe2b7c53cc3c'
uuid = 'b1d9769d-94a8-427d-8ec6-fe2b7c53cc3c::882a0bdf-1be0-41bd-94a9-88d6c0272e8a'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/personalinformation/dna/dist/dna.dna.json'
hash = 'QmcFAqAnG28WkMWFPKw72NxNqgjJvK96eNBuYuGHnntLHM'
id = 'personalinformation-test::ca9afbeb-1aa1-4eca-b4e0-65ce4c91b1fc'
uuid = 'ca9afbeb-1aa1-4eca-b4e0-65ce4c91b1fc::882a0bdf-1be0-41bd-94a9-88d6c0272e8a'

[[dnas]]
file = '/Users/philipbeadle/holochain/CRISPR/dna/freckles/dna/dist/dna.dna.json'
hash = 'QmQPDstS9YrwHskxfZkF8n5XFZzcW231m4ULLGg3M2RLLR'
id = 'freckles-test::3669b21e-4fa8-4b66-afd9-fb0576143b58'
uuid = '3669b21e-4fa8-4b66-afd9-fb0576143b58::882a0bdf-1be0-41bd-94a9-88d6c0272e8a'

[[instances]]
agent = 'ef5ba968-0048-4135-b831-a86b615a89b2'
dna = 'projects-test::09e3dd55-68f5-4df4-9866-8e8107c22276'
id = 'ef5ba968-0048-4135-b831-a86b615a89b2'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/WnhPtW/ef5ba968-0048-4135-b831-a86b615a89b2'
type = 'lmdb'

[[instances]]
agent = '57c01ed8-30ae-4fca-b6f9-40192821fed2'
dna = 'origins-test::14005bc1-f5b9-434d-8e05-23188c3813f6'
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/WnhPtW/57c01ed8-30ae-4fca-b6f9-40192821fed2'
type = 'lmdb'

[[instances]]
agent = '164449a2-e7d4-47dc-acc8-2fe317b8d9fe'
dna = 'origins-test::48e7f196-93f4-4514-9994-ffd27512bd36'
id = '164449a2-e7d4-47dc-acc8-2fe317b8d9fe'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/WnhPtW/164449a2-e7d4-47dc-acc8-2fe317b8d9fe'
type = 'lmdb'

[[instances]]
agent = '95569e2e-0de2-4073-8a7d-579f87534c04'
dna = 'kanban-test::5b8b5157-ee45-4016-aa06-5f0f44fbfc65'
id = '95569e2e-0de2-4073-8a7d-579f87534c04'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/WnhPtW/95569e2e-0de2-4073-8a7d-579f87534c04'
type = 'lmdb'

[[instances]]
agent = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'
dna = 'notes-test::310601c6-a594-4ce7-a21f-5c97d5e7ce41'
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/WnhPtW/a23de7fe-bff7-4e6e-87f0-f4c44d038888'
type = 'lmdb'

[[instances]]
agent = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
dna = 'tasks-test::edbb4b96-7768-47ad-b9a7-bdb31462225d'
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/WnhPtW/e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'
type = 'lmdb'

[[instances]]
agent = 'fields'
dna = 'fields-test::b1d9769d-94a8-427d-8ec6-fe2b7c53cc3c'
id = 'fields'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/WnhPtW/fields'
type = 'lmdb'

[[instances]]
agent = 'personalinformation'
dna = 'personalinformation-test::ca9afbeb-1aa1-4eca-b4e0-65ce4c91b1fc'
id = 'personalinformation'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/WnhPtW/personalinformation'
type = 'lmdb'

[[instances]]
agent = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
dna = 'freckles-test::3669b21e-4fa8-4b66-afd9-fb0576143b58'
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'

[instances.storage]
path = '/tmp/tmp.OGr2YY1n4S/tryorama/WnhPtW/0098d2a1-5668-4a5a-8ef8-503d58dd38ce'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'ef5ba968-0048-4135-b831-a86b615a89b2'

[[interfaces.instances]]
id = '57c01ed8-30ae-4fca-b6f9-40192821fed2'

[[interfaces.instances]]
id = '164449a2-e7d4-47dc-acc8-2fe317b8d9fe'

[[interfaces.instances]]
id = '95569e2e-0de2-4073-8a7d-579f87534c04'

[[interfaces.instances]]
id = 'a23de7fe-bff7-4e6e-87f0-f4c44d038888'

[[interfaces.instances]]
id = 'e1289ae4-0611-4c5c-b1fa-5b4ed0b8c67a'

[[interfaces.instances]]
id = 'fields'

[[interfaces.instances]]
id = 'personalinformation'

[[interfaces.instances]]
id = '0098d2a1-5668-4a5a-8ef8-503d58dd38ce'

[interfaces.driver]
port = 33005
type = 'websocket'

[logger]
state_dump = true
type = 'error'
[[logger.rules.rules]]
exclude = true
pattern = '.*parity.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*mio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*tokio.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*hyper.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rusoto_core.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*want.*'

[[logger.rules.rules]]
exclude = true
pattern = '.*rpc.*'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
